/* Shared campaign scope and simple hotel-funded extras. */
(function(){
const T=BookeseTarget,E=T.esc,propertyMarket='Đà Nẵng';
const catalog=['Nâng hạng phòng miễn phí','Voucher ăn uống','Đưa hoặc đón sân bay một chiều','Đưa đón sân bay hai chiều','City tour','Check-in sớm / Check-out muộn','Quyền lợi khác'];
const markets=['Đà Nẵng','Phú Quốc','Nha Trang','Đà Lạt','Hà Nội','TP. Hồ Chí Minh'];
const allowed=p=>p&&(!p.markets?.length||p.markets.includes(propertyMarket));
const options=p=>Array.isArray(p.benefitOptions)?p.benefitOptions:typeof p.benefitOptions==='string'?[p.benefitOptions]:catalog;
const summary=(p,price)=>`<p><b>Thị trường:</b> ${E((Array.isArray(p.markets)?p.markets.join(', '):p.markets)||'Tất cả điểm đến')}${price?` · <b>Quyền lợi tặng kèm:</b> ${price.benefitRequired===true||price.benefitRequired==='yes'?'Bắt buộc chọn ít nhất một':'Tùy chọn'}`:''}</p>`;
const list=xs=>`<ul class="benefit-description-list">${(xs||[]).map(x=>`<li><b>${E(x.name)}</b><p>${E(x.description)}</p></li>`).join('')}</ul>`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date());
window.CampaignExtras={allowed,options,summary,list};

const validExtras=(r,p)=>(!p.benefitRequired||!!r.extras?.length)&&(r.extras||[]).every(x=>options(p).includes(x.name)&&x.description?.trim());
// Migrate legacy round-level settings without discarding existing registrations.
if(T.read().programs.some(g=>Object.hasOwn(g,'benefitOptions')||Object.hasOwn(g,'benefitRequired'))){T.update(d=>{d.programs.forEach(g=>{if(!Object.hasOwn(g,'benefitOptions')&&!Object.hasOwn(g,'benefitRequired'))return;d.prices.filter(p=>p.program===g.id).forEach(p=>{if(!Object.hasOwn(p,'benefitOptions'))p.benefitOptions=[...options(g)];if(!Object.hasOwn(p,'benefitRequired'))p.benefitRequired=g.benefitRequired===true||g.benefitRequired==='yes'});delete g.benefitOptions;delete g.benefitRequired})},'Chuyển cấu hình quyền lợi hiện có vào từng khung ưu đãi giá')}
const extraStyle=document.createElement('style');extraStyle.textContent=`
.benefit-description-list{list-style:none;padding:0;margin:12px 0}.benefit-description-list li{padding:10px 0;border-bottom:1px solid #e3e9ee}.benefit-description-list li:last-child{border:0}.benefit-description-list p{margin:5px 0;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.5}
.benefit-review-cell{min-width:220px;max-width:320px}.benefit-review-cell p{margin:5px 0 12px;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.45}
.stay-benefits{margin:12px 0 16px;padding:12px 14px;border:1px solid #d8e8df;border-radius:8px;background:#f6fbf8;color:#234b3b;text-align:left}.stay-benefits__top{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.stay-benefits__title{display:flex;align-items:center;gap:7px;font-size:14px;font-weight:600}.stay-benefits__title svg{width:17px;height:17px;flex:none}.stay-benefits__tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:9px}.stay-benefits__tag{font-size:13px;line-height:1.4;padding:4px 8px;border:1px solid #d7e7dd;border-radius:4px;background:white;color:#24573f}.stay-benefits button.stay-benefits__link{padding:2px 0;border:0;background:none;color:#0066e8;font-size:13px;text-decoration:underline;cursor:pointer}.stay-benefits__context{margin:9px 0 0;font-size:12px;color:#627568;line-height:1.5}.stay-benefits button:focus-visible{outline:2px solid #0066ff;outline-offset:3px}.stay-benefits--detail{margin:18px 0}.stay-benefits--checkout .benefit-description-list{font-size:14px;color:#334155}
`;document.head.appendChild(extraStyle);
if(location.pathname.endsWith('intranet.html')){
 const priorForm=programForm;
 programForm=function(id){priorForm(id);const p=T.read().programs.find(p=>p.id===id)||{},f=document.querySelector('#pf');f.querySelector('.actions').insertAdjacentHTML('beforebegin',`<fieldset><legend>Thị trường điểm đến áp dụng</legend><label><input type="radio" name="marketScope" value="all" ${!p.markets?.length?'checked':''}> Tất cả điểm đến</label> <label><input type="radio" name="marketScope" value="selected" ${p.markets?.length?'checked':''}> Chọn điểm đến</label><div id="destinationChoices" class="checks" style="margin-top:12px">${markets.map(m=>`<label><input type="checkbox" name="markets" value="${E(m)}" ${p.markets?.includes(m)?'checked':''}> ${E(m)}</label>`).join('')}</div></fieldset>`);
 const toggle=()=>{document.querySelector('#destinationChoices').style.display=f.marketScope.value==='all'?'none':'flex'};f.querySelectorAll('[name=marketScope]').forEach(x=>x.onchange=toggle);toggle();
 const submit=f.onsubmit;f.onsubmit=ev=>{const fd=new FormData(f),selected=fd.getAll('markets');if((fd.get('marketScope')==='selected'&&!selected.length)){ev.preventDefault();document.querySelector('#pfError').textContent='Chọn ít nhất một điểm đến.';return}submit(ev);if(document.querySelector('#modal').open)return;T.update(d=>{const saved=d.programs.find(x=>x.id===programId);saved.markets=fd.get('marketScope')==='all'?[]:selected;if(id)saved.status=p.status},'Lưu phạm vi điểm đến của đợt tiếp thị');programDetail()};if(id)f.querySelector('button.primary').textContent='Lưu thay đổi'};
 const priorPriceForm=priceForm;
 priceForm=function(id){priorPriceForm(id);const p=T.read().prices.find(x=>x.id===id)||{},f=document.querySelector('#priceForm'),ids=new Set(T.read().prices.map(x=>x.id));f.querySelector('.actions').insertAdjacentHTML('beforebegin',`<fieldset style="margin-top:16px"><legend>Quyền lợi tặng kèm do chỗ nghỉ cung cấp</legend><label class="field">Yêu cầu tham gia<select name="benefitRequired"><option value="no">Tùy chọn</option><option value="yes" ${p.benefitRequired?'selected':''}>Bắt buộc chọn ít nhất một quyền lợi</option></select></label><p class="muted">Áp dụng riêng cho khung ưu đãi này. Chọn các loại cho phép khách sạn đăng ký. Khách sạn nhập mô tả chi tiết; nội dung được hiển thị cho khách sau khi Bookese duyệt.</p>${catalog.map(n=>`<label style="display:block;margin:8px 0"><input type="checkbox" name="benefitOptions" value="${E(n)}" ${options(p).includes(n)?'checked':''}> ${E(n)}</label>`).join('')}</fieldset>`);const submit=f.onsubmit;f.onsubmit=ev=>{const fd=new FormData(f),bs=fd.getAll('benefitOptions'),must=fd.get('benefitRequired')==='yes';if(must&&!bs.length){ev.preventDefault();f.querySelector('#priceError').textContent='Chọn ít nhất một loại quyền lợi cho khung ưu đãi bắt buộc.';return}submit(ev);if(document.querySelector('#modal').open)return;T.update(d=>{const saved=d.prices.find(x=>id?x.id===id:!ids.has(x.id));saved.benefitOptions=bs;saved.benefitRequired=must},'Lưu quyền lợi tặng kèm của khung ưu đãi giá');programDetail()}};
 const priorDetail=programDetail;
 const registrationBody=r=>{const d=T.read(),p=d.prices.find(x=>x.id===r.price),g=d.programs.find(x=>x.id===p?.program);return `<h3>Awaken Da Nang Hotel</h3><p>${E(p?.name)} · Giảm ${E(r.rate)}%</p>${summary(g,p)}<p><b>Phòng / loại giá:</b> ${E((r.roomRates||[]).map(v=>v.replace('deluxe','Deluxe').replace('suite','Suite').replace('|nonref',' · Không hoàn hủy').replace('|flex',' · Linh hoạt')).join(', '))}</p><p><b>Lưu trú:</b> ${E(p?.stayStart)} → ${E(p?.stayEnd)}</p><h3>Quyền lợi khách sạn cam kết</h3>${r.extras?.length?list(r.extras):'<p>Không đăng ký quyền lợi tặng kèm.</p>'}`};
 window.showRegistrationExtras=id=>{const r=T.read().registrations.find(x=>String(x.id)===String(id));if(r)modal('Chi tiết đăng ký tham gia',registrationBody(r)+`<p><b>Trạng thái:</b> ${E(r.status)}</p><div class="actions"><button onclick="closeModal()">Đóng</button></div>`)};
 programDetail=function(){priorDetail();const p=targetProgram();if(!p)return;document.querySelector('#app .card').insertAdjacentHTML('beforeend',summary(p));const d=T.read(),sections=[...document.querySelectorAll('#app section')],prices=d.prices.filter(x=>x.program===p.id),priceSection=sections.find(s=>s.querySelector('h2')?.textContent==='Ưu đãi giá chỗ nghỉ');priceSection.querySelector('thead tr').insertAdjacentHTML('beforeend','<th>Quyền lợi tặng kèm</th>');[...priceSection.querySelectorAll('tbody tr')].forEach((tr,i)=>{if(prices[i])tr.insertAdjacentHTML('beforeend',`<td><b>${prices[i].benefitRequired===true||prices[i].benefitRequired==='yes'?'Bắt buộc chọn ít nhất một':'Tùy chọn'}</b><p class="muted">${E(options(prices[i]).join(' · ')||'Không cấu hình')}</p></td>`);else tr.cells[0].colSpan=6});[...priceSection.querySelectorAll('tr')].forEach(tr=>{if(tr.cells.length===6)tr.insertBefore(tr.cells[5],tr.cells[2])});priceSection.querySelector('thead tr').cells[5].textContent='Thao tác';const section=sections.find(s=>s.querySelector('h2')?.textContent==='Chỗ nghỉ đăng ký');section.querySelector('thead tr').cells[3].insertAdjacentHTML('beforebegin','<th>Quyền lợi tặng kèm</th>');section.querySelector('thead tr').cells[5].textContent='Thao tác';const regs=d.registrations.filter(r=>prices.some(x=>x.id===r.price));[...section.querySelectorAll('tbody tr')].forEach((tr,i)=>{const r=regs[i];if(!r){tr.cells[0].colSpan=6;return}tr.cells[3].insertAdjacentHTML('beforebegin',`<td class="benefit-review-cell">${r.extras?.length?r.extras.map(x=>`<b>${E(x.name)}</b><p>${E(x.description)}</p>`).join(''):'<span class="muted">Không đăng ký</span>'}</td>`);const btn=document.createElement('button');btn.textContent='Xem chi tiết';btn.onclick=()=>showRegistrationExtras(r.id);tr.cells[5].prepend(btn)})};
 const priorReview=reviewRegistration;
 reviewRegistration=function(id,ok){const d=T.read(),r=d.registrations.find(x=>x.id===id),p=d.prices.find(x=>x.id===r?.price),g=d.programs.find(x=>x.id===p?.program);if(!r)return;priorReview(id,ok);const f=document.querySelector('#reviewForm');if(!f)return;f.querySelector(':scope > p')?.remove();f.insertAdjacentHTML('afterbegin',registrationBody(r));const submit=f.onsubmit;f.onsubmit=ev=>{if(ok&&(!allowed(g)||!validExtras(r,p))){ev.preventDefault();f.querySelector('#reviewError').textContent='Kiểm tra điểm đến, quyền lợi bắt buộc và mô tả theo khung ưu đãi trước khi duyệt.';return}submit(ev)}};
 nav();
}
if(location.pathname.endsWith('promotions.html')){
 const priorCampaigns=targetCampaigns;
 targetCampaigns=function(){priorCampaigns();const d=T.read(),cards=[...document.querySelectorAll('#content .bookese-option')];cards.forEach((card,i)=>{const price=d.prices[i],p=d.programs.find(x=>x.id===price?.program),r=d.registrations.find(x=>x.price===price?.id);if(!allowed(p)||(['Nháp','Chờ duyệt'].includes(p.status)&&!r)){card.remove();return}card.querySelector('h3').insertAdjacentHTML('afterend',summary(p,price));if(r?.extras?.length)card.querySelector('div').insertAdjacentHTML('beforeend',`<h4>Quyền lợi đã đăng ký</h4>${list(r.extras)}`)});if(!document.querySelector('#content .bookese-option'))document.querySelector('#content section').insertAdjacentHTML('beforeend','<p class="empty">Chưa có chiến dịch phù hợp với điểm đến của chỗ nghỉ.</p>')};
 const priorRegistration=registrationForm;
 registrationForm=function(id){const d=T.read(),price=d.prices.find(x=>x.id===id),p=d.programs.find(x=>x.id===price?.program),r=d.registrations.find(x=>x.price===id);if(!allowed(p)){toast('Chỗ nghỉ không thuộc điểm đến của chiến dịch.');return}priorRegistration(id);const f=document.querySelector('#rf');f.querySelector('.actions').insertAdjacentHTML('beforebegin',`<fieldset><legend>Quyền lợi tặng kèm cho khách</legend>${summary(p,price)}<p>Chọn quyền lợi và nhập mô tả để khách đọc. Ghi rõ điều kiện như tùy tình trạng phòng, số người, số lần hoặc yêu cầu đặt trước nếu có.</p>${options(price).map((name,i)=>{const value=r?.extras?.find(x=>x.name===name);return `<div style="margin:12px 0"><label><input type="checkbox" name="extraChoice" value="${i}" ${value?'checked':''}> ${E(name)}</label><textarea aria-label="Mô tả ${E(name)}" data-extra="${i}" style="display:block;width:100%;margin-top:8px;min-height:65px" maxlength="1000" placeholder="Nhập quyền lợi và điều kiện sử dụng">${E(value?.description||'')}</textarea></div>`}).join('')}</fieldset>`);const toggle=()=>f.querySelectorAll('[name=extraChoice]').forEach(c=>{const t=f.querySelector(`[data-extra="${c.value}"]`);t.style.display=c.checked?'block':'none';t.disabled=!c.checked;t.required=c.checked});f.querySelectorAll('[name=extraChoice]').forEach(c=>c.onchange=toggle);toggle();const submit=f.onsubmit;f.onsubmit=ev=>{const extras=[...f.querySelectorAll('[name=extraChoice]:checked')].map(c=>({name:options(price)[+c.value],description:f.querySelector(`[data-extra="${c.value}"]`).value.trim()}));if(!validExtras({extras},price)){ev.preventDefault();document.querySelector('#regError').textContent='Chọn ít nhất một quyền lợi khi bắt buộc và nhập mô tả cho từng quyền lợi đã chọn.';return}submit(ev);if(document.querySelector('#dialog').open)return;T.update(d=>{d.registrations.find(x=>x.price===id).extras=extras},'Lưu mô tả quyền lợi tặng kèm chờ Bookese duyệt');targetRender()}};
 targetRender();
}
if(location.pathname.endsWith('customer.html')){
 const previousSource=sourceOffers;
 sourceOffers=function(){const result=previousSource();result.items=result.items.filter(x=>x.group!=='campaign'||!result.d.programs.some(p=>p.id===x.program)||allowed(result.d.programs.find(p=>p.id===x.program)));return result};
 const previousApproved=approvedPrograms;
 approvedPrograms=function(){return previousApproved().filter(x=>{const g=T.read().programs.find(p=>p.id===x.p.program);return !g||allowed(g)})};
 function eligible(room){const d=T.read();return d.registrations.filter(r=>r.status==='Đã tham gia'&&r.extras?.length).flatMap(r=>{const p=d.prices.find(x=>x.id===r.price),g=d.programs.find(x=>x.id===p?.program);if(!allowed(g)||!p||p.status!=='Đang mở'||!['Đang mở','Tạm ngưng'].includes(g.status))return [];if(r.roomRates?.length&&!r.roomRates.includes(room+'|flex'))return [];const book=typeof P!=='undefined'?P.date('2026-09-18',0):today();if(book<p.start||book>p.end)return [];const dates=[];for(let dt=customer.stay;dt<customer.end;dt=P.date(dt,1))if(dt>=p.stayStart&&dt<=p.stayEnd&&!(p.excluded||[]).includes(dt))dates.push(dt);if(!dates.length)return [];return [{program:g.name,price:p.id,dates,extras:r.extras}]})}
 const giftIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M3 9h18v4H3zM5 13v8h14v-8M12 9v12M12 9H8a3 3 0 1 1 3-3l1 3Zm0 0h4a3 3 0 1 0-3-3l-1 3Z"/></svg>';
 const dateLabel=dates=>dates.map(s=>s.split('-').reverse().join('/')).join(', ');
 window.showStayBenefits=room=>{const xs=eligible(room);modal('Quà tặng từ khách sạn',xs.length?`<p>Awaken Da Nang Hotel · Phòng ${room==='deluxe'?'Deluxe':'Suite'}</p>${xs.map(x=>`<h3>${E(x.program)}</h3><p class="muted">Ngày lưu trú ${E(dateLabel(x.dates))}</p>${list(x.extras)}`).join('')}<p class="muted">Khách sạn cung cấp quyền lợi theo điều kiện trên. Số lượng quà theo mô tả, không tự nhân theo số đêm.</p>`:'<p>Chưa có quyền lợi phù hợp với phòng và ngày đang chọn.</p>')};
 const block=(room,mode='compact')=>{const xs=eligible(room);if(!xs.length)return '';const names=[...new Set(xs.flatMap(x=>x.extras.map(e=>e.name)))];return `<section class="stay-benefits stay-benefits--${mode}" aria-label="Quà tặng từ khách sạn"><div class="stay-benefits__top"><span class="stay-benefits__title">${giftIcon}Quà tặng từ khách sạn</span><button type="button" class="stay-benefits__link" onclick="showStayBenefits('${room}')">Xem điều kiện</button></div><div class="stay-benefits__tags">${names.map(n=>`<span class="stay-benefits__tag">${E(n)}</span>`).join('')}</div>${mode!=='compact'?`<p class="stay-benefits__context">Phòng ${room==='deluxe'?'Deluxe':'Suite'} · ${E(dateLabel([...new Set(xs.flatMap(x=>x.dates))]))}</p>`:''}${mode==='checkout'?xs.map(x=>list(x.extras)).join(''):''}</section>`};
 const oldHotel=hotel;hotel=function(){return oldHotel().replace('<h3 id="rooms">',block(customer.room,'detail')+'<h3 id="rooms">')};
 const oldCard=hotelCard;hotelCard=function(name,img,room){const html=oldCard(name,img,room);return room==='deluxe'?html.replace('<div class="search-room-summary">',block(room)+'<div class="search-room-summary">'):html};
 const oldCheckout=checkout;checkout=function(){return oldCheckout().replace('<div class="checkout-hotel">',block(customer.room,'checkout')+'<div class="checkout-hotel">')};
 const oldFinish=finishSample;finishSample=function(){oldFinish();if(document.querySelector('#detail')?.textContent.includes('Đặt phòng mẫu đã được kiểm tra')){const snapshot={at:new Date().toISOString(),stay:customer.stay,end:customer.end,room:customer.room,quantity:customer.quantity,benefits:eligible(customer.room)};localStorage.setItem('bookese-last-sample-benefits',JSON.stringify(snapshot));document.querySelector('#detail').insertAdjacentHTML('beforeend','<p>Đã lưu quyền lợi tặng kèm vào bản xác nhận mẫu trên trình duyệt.</p>')}};
 renderCustomer();
}
})();
