/* Shared campaign scope and simple hotel-funded extras. */
(function(){
const T=BookeseTarget,E=T.esc,propertyMarket='Đà Nẵng';
const catalog=['Nâng hạng phòng miễn phí','Voucher ăn uống','Đưa hoặc đón sân bay một chiều','Đưa đón sân bay hai chiều','City tour','Check-in sớm / Check-out muộn','Quyền lợi khác'];
const markets=['Đà Nẵng','Phú Quốc','Nha Trang','Đà Lạt','Hà Nội','TP. Hồ Chí Minh'];
const allowed=p=>p&&(!p.markets?.length||p.markets.includes(propertyMarket));
const options=p=>Array.isArray(p.benefitOptions)?p.benefitOptions:typeof p.benefitOptions==='string'?[p.benefitOptions]:catalog;
const summary=p=>`<p><b>Điểm đến:</b> ${E((Array.isArray(p.markets)?p.markets.join(', '):p.markets)||'Tất cả điểm đến')} · <b>Quyền lợi tặng kèm:</b> ${p.benefitRequired===true||p.benefitRequired==='yes'?'Bắt buộc chọn ít nhất một':'Tùy chọn'}</p>`;
const list=xs=>`<ul>${(xs||[]).map(x=>`<li><b>${E(x.name)}</b>: ${E(x.description)}</li>`).join('')}</ul>`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date());
window.CampaignExtras={allowed,options,summary,list};
if(location.pathname.endsWith('intranet.html')){
 const priorForm=programForm;
 programForm=function(id){priorForm(id);const p=T.read().programs.find(p=>p.id===id)||{},f=document.querySelector('#pf');f.querySelector('.actions').insertAdjacentHTML('beforebegin',`<fieldset><legend>Thị trường điểm đến áp dụng</legend><label><input type="radio" name="marketScope" value="all" ${!p.markets?.length?'checked':''}> Tất cả điểm đến</label> <label><input type="radio" name="marketScope" value="selected" ${p.markets?.length?'checked':''}> Chọn điểm đến</label><div id="destinationChoices" class="checks" style="margin-top:12px">${markets.map(m=>`<label><input type="checkbox" name="markets" value="${E(m)}" ${p.markets?.includes(m)?'checked':''}> ${E(m)}</label>`).join('')}</div></fieldset><fieldset style="margin-top:16px"><legend>Quyền lợi tặng kèm do chỗ nghỉ cung cấp</legend><label class="field">Yêu cầu tham gia<select name="benefitRequired"><option value="no">Tùy chọn</option><option value="yes" ${p.benefitRequired?'selected':''}>Bắt buộc chọn ít nhất một quyền lợi</option></select></label><p class="muted">Chọn các loại cho phép khách sạn đăng ký. Khách sạn nhập mô tả chi tiết; nội dung được hiển thị cho khách sau khi Bookese duyệt.</p>${catalog.map(n=>`<label style="display:block;margin:8px 0"><input type="checkbox" name="benefitOptions" value="${E(n)}" ${options(p).includes(n)?'checked':''}> ${E(n)}</label>`).join('')}</fieldset>`);
 const toggle=()=>{document.querySelector('#destinationChoices').style.display=f.marketScope.value==='all'?'none':'flex'};f.querySelectorAll('[name=marketScope]').forEach(x=>x.onchange=toggle);toggle();
 const submit=f.onsubmit;f.onsubmit=ev=>{const fd=new FormData(f),selected=fd.getAll('markets'),bs=fd.getAll('benefitOptions'),required=fd.get('benefitRequired')==='yes';if((fd.get('marketScope')==='selected'&&!selected.length)||(required&&!bs.length)){ev.preventDefault();document.querySelector('#pfError').textContent='Chọn ít nhất một điểm đến; nếu bắt buộc quyền lợi thì chọn ít nhất một loại quyền lợi.';return}submit(ev);if(document.querySelector('#modal').open)return;T.update(d=>{const saved=d.programs.find(x=>x.id===programId);saved.markets=fd.get('marketScope')==='all'?[]:selected;saved.benefitOptions=bs;saved.benefitRequired=required;if(id)saved.status=p.status},'Lưu phạm vi điểm đến và quyền lợi tặng kèm');programDetail()};if(id)f.querySelector('button.primary').textContent='Lưu thay đổi'};
 const priorDetail=programDetail;
 programDetail=function(){priorDetail();const p=targetProgram();if(!p)return;document.querySelector('#app .card').insertAdjacentHTML('beforeend',summary(p)+`<p class="muted">Quyền lợi cho phép: ${E(options(p).join(' · ')||'Không yêu cầu quyền lợi tặng kèm')}. Khách sạn chọn và nhập mô tả khi đăng ký.</p>`);const section=[...document.querySelectorAll('#app section')].find(s=>s.querySelector('h2')?.textContent==='Chỗ nghỉ đăng ký');if(!section)return;const regs=T.read().registrations.filter(r=>T.read().prices.some(x=>x.id===r.price&&x.program===p.id));[...section.querySelectorAll('tbody tr')].forEach((tr,i)=>{if(regs[i]?.extras?.length)tr.cells[0].insertAdjacentHTML('beforeend',`<details><summary>Quyền lợi tặng kèm (${regs[i].extras.length})</summary>${list(regs[i].extras)}</details>`)})};
 const priorReview=reviewRegistration;
 reviewRegistration=function(id,ok){const d=T.read(),r=d.registrations.find(x=>x.id===id),p=d.programs.find(x=>x.id===d.prices.find(y=>y.id===r?.price)?.program);if(ok&&(!allowed(p)||(p.benefitRequired&&!r.extras?.length))){toast('Chỗ nghỉ ngoài điểm đến áp dụng hoặc chưa đăng ký quyền lợi bắt buộc.');return}priorReview(id,ok);document.querySelector('#reviewForm')?.insertAdjacentHTML('afterbegin',`<h3>Quyền lợi khách sạn cam kết</h3>${r.extras?.length?list(r.extras):'<p>Không đăng ký quyền lợi tặng kèm.</p>'}<p class="muted">Nội dung được hiển thị cho khách sau khi duyệt. Kiểm tra mô tả, điều kiện sử dụng và phạm vi phòng/ngày.</p>`)};
 nav();
}
if(location.pathname.endsWith('promotions.html')){
 const priorCampaigns=targetCampaigns;
 targetCampaigns=function(){priorCampaigns();const d=T.read(),cards=[...document.querySelectorAll('#content .bookese-option')];cards.forEach((card,i)=>{const price=d.prices[i],p=d.programs.find(x=>x.id===price?.program),r=d.registrations.find(x=>x.price===price?.id);if(!allowed(p)||(['Nháp','Chờ duyệt'].includes(p.status)&&!r)){card.remove();return}card.querySelector('h3').insertAdjacentHTML('afterend',summary(p));if(r?.extras?.length)card.querySelector('div').insertAdjacentHTML('beforeend',`<h4>Quyền lợi đã đăng ký</h4>${list(r.extras)}`)});if(!document.querySelector('#content .bookese-option'))document.querySelector('#content section').insertAdjacentHTML('beforeend','<p class="empty">Chưa có chiến dịch phù hợp với điểm đến của chỗ nghỉ.</p>')};
 const priorRegistration=registrationForm;
 registrationForm=function(id){const d=T.read(),price=d.prices.find(x=>x.id===id),p=d.programs.find(x=>x.id===price?.program),r=d.registrations.find(x=>x.price===id);if(!allowed(p)){toast('Chỗ nghỉ không thuộc điểm đến của chiến dịch.');return}priorRegistration(id);const f=document.querySelector('#rf');f.querySelector('.actions').insertAdjacentHTML('beforebegin',`<fieldset><legend>Quyền lợi tặng kèm cho khách</legend>${summary(p)}<p>Chọn quyền lợi và nhập mô tả để khách đọc. Ghi rõ điều kiện như tùy tình trạng phòng, số người, số lần hoặc yêu cầu đặt trước nếu có.</p>${options(p).map((name,i)=>{const value=r?.extras?.find(x=>x.name===name);return `<div style="margin:12px 0"><label><input type="checkbox" name="extraChoice" value="${i}" ${value?'checked':''}> ${E(name)}</label><textarea aria-label="Mô tả ${E(name)}" data-extra="${i}" style="display:block;width:100%;margin-top:8px;min-height:65px" maxlength="1000" placeholder="Nhập quyền lợi và điều kiện sử dụng">${E(value?.description||'')}</textarea></div>`}).join('')}</fieldset>`);const toggle=()=>f.querySelectorAll('[name=extraChoice]').forEach(c=>{const t=f.querySelector(`[data-extra="${c.value}"]`);t.style.display=c.checked?'block':'none';t.disabled=!c.checked;t.required=c.checked});f.querySelectorAll('[name=extraChoice]').forEach(c=>c.onchange=toggle);toggle();const submit=f.onsubmit;f.onsubmit=ev=>{const extras=[...f.querySelectorAll('[name=extraChoice]:checked')].map(c=>({name:options(p)[+c.value],description:f.querySelector(`[data-extra="${c.value}"]`).value.trim()}));if((p.benefitRequired&&!extras.length)||extras.some(x=>!x.description)){ev.preventDefault();document.querySelector('#regError').textContent='Chọn ít nhất một quyền lợi khi bắt buộc và nhập mô tả cho từng quyền lợi đã chọn.';return}submit(ev);if(document.querySelector('#dialog').open)return;T.update(d=>{d.registrations.find(x=>x.price===id).extras=extras},'Lưu mô tả quyền lợi tặng kèm chờ Bookese duyệt');targetRender()}};
 targetRender();
}
if(location.pathname.endsWith('customer.html')){
 const previousSource=sourceOffers;
 sourceOffers=function(){const result=previousSource();result.items=result.items.filter(x=>x.group!=='campaign'||!result.d.programs.some(p=>p.id===x.program)||allowed(result.d.programs.find(p=>p.id===x.program)));return result};
 const previousApproved=approvedPrograms;
 approvedPrograms=function(){return previousApproved().filter(x=>{const g=T.read().programs.find(p=>p.id===x.p.program);return !g||allowed(g)})};
 function eligible(room){const d=T.read();return d.registrations.filter(r=>r.status==='Đã tham gia'&&r.extras?.length).flatMap(r=>{const p=d.prices.find(x=>x.id===r.price),g=d.programs.find(x=>x.id===p?.program);if(!allowed(g)||!p||p.status!=='Đang mở'||!['Đang mở','Tạm ngưng'].includes(g.status))return [];if(r.roomRates?.length&&!r.roomRates.includes(room+'|flex'))return [];const book=typeof P!=='undefined'?P.date('2026-09-18',0):today();if(book<p.start||book>p.end)return [];const dates=[];for(let dt=customer.stay;dt<customer.end;dt=P.date(dt,1))if(dt>=p.stayStart&&dt<=p.stayEnd&&!(p.excluded||[]).includes(dt))dates.push(dt);if(!dates.length)return [];return [{program:g.name,price:p.id,dates,extras:r.extras}]})}
 const block=room=>{const xs=eligible(room);return xs.length?`<section class="card" style="padding:16px;border:1px solid #dce9e4;margin:16px 0"><h3>Quyền lợi tặng kèm từ chỗ nghỉ</h3>${xs.map(x=>`<p><b>${E(x.program)}</b></p>${list(x.extras)}<small>Áp dụng cho phòng đang chọn, ngày lưu trú ${x.dates.map(E).join(', ')}. ${E('Điều kiện sử dụng theo mô tả của chỗ nghỉ.')}</small>`).join('')}</section>`:''};
 const oldHotel=hotel;hotel=function(){return oldHotel().replace('<h3 id="rooms">',block(customer.room)+'<h3 id="rooms">')};
 const oldCard=hotelCard;hotelCard=function(name,img,room){const html=oldCard(name,img,room);if(room!=='deluxe')return html;const xs=eligible(room);return xs.length?html.replace('<div class="search-room-summary">',`<details style="margin:12px 0"><summary>Quyền lợi tặng kèm từ chỗ nghỉ</summary>${xs.map(x=>list(x.extras)).join('')}</details><div class="search-room-summary">`):html};
 const oldCheckout=checkout;checkout=function(){return oldCheckout().replace('<div class="checkout-hotel">',block(customer.room)+'<div class="checkout-hotel">')};
 const oldFinish=finishSample;finishSample=function(){oldFinish();if(document.querySelector('#detail')?.textContent.includes('Đặt phòng mẫu đã được kiểm tra')){const snapshot={at:new Date().toISOString(),stay:customer.stay,end:customer.end,room:customer.room,quantity:customer.quantity,benefits:eligible(customer.room)};localStorage.setItem('bookese-last-sample-benefits',JSON.stringify(snapshot));document.querySelector('#detail').insertAdjacentHTML('beforeend','<p>Đã lưu quyền lợi tặng kèm vào bản xác nhận mẫu trên trình duyệt.</p>')}};
 renderCustomer();
}
})();
