(function(root){
'use strict';
const tiers=['Thành viên','Thân thiết','Trung thành'];
const int=n=>Number.isSafeInteger(Number(n))&&Number(n)>=0;
function spendLimit({total,voucher=0,available=0,monthUsed=0}){if(![total,voucher,monthUsed].every(int)||!Number.isSafeInteger(Number(available))||voucher>total)throw Error('Kiểm tra tổng tiền, voucher, số dư và hạn mức.');return Math.max(0,Math.min(Math.floor(total*.3),2000000,5000000-monthUsed,Math.max(0,Number(available)),total-voucher));}
function stay({total,voucher=0,spent=0,tier=0}){if(![total,voucher,spent].every(int)||voucher+spent>total||![0,1,2].includes(+tier))throw Error('Số tiền giảm vượt tổng tiền hoặc hạng không hợp lệ.');return Math.floor((total-voucher-spent)*(+tier+1)/100);}
function flight({fee,tier=0,international=false}){if(!int(fee)||![0,1,2].includes(+tier))throw Error('Phí dịch vụ hoặc hạng không hợp lệ.');return Math.min([10000,15000,20000][tier]*(international?3:1),Math.floor(fee*.5));}
function allocate(lots,amount,today){if(!int(amount))throw Error('Số xu phải là số nguyên không âm.');let left=+amount;const parts=[];for(const l of [...lots].filter(l=>l.status==='Khả dụng'&&l.expiry>=today).sort((a,b)=>a.expiry.localeCompare(b.expiry)||a.credit.localeCompare(b.credit)||a.id.localeCompare(b.id))){const n=Math.min(left,l.remaining);if(n>0)parts.push({lot:l.id,amount:n,expiry:l.expiry});left-=n;if(!left)break;}if(left)throw Error('Không đủ xu khả dụng.');return parts;}
function refund({spent,earned,percent,returned=0,recovered=0,expired=false,service=false,sameMonth=true}){if(![spent,earned,returned,recovered].every(int)||!Number.isFinite(+percent)||percent<0||percent>100)throw Error('Tỷ lệ hoàn phải từ 0 đến 100%.');const back=Math.max(0,Math.floor(spent*percent/100)-returned),revoke=Math.max(0,Math.floor(earned*percent/100)-recovered);return {back,revoke,available:expired&&!service?0:back,expired:expired&&!service?back:0,compensation:expired&&service?back:0,quota:sameMonth?back:0};}
function amend({total,voucher,oldSpent,oldTier,tier}){const spent=Math.min(oldSpent,Math.floor(total*.3),2000000);if(voucher+spent>total)throw Error('Voucher và xu vượt giá mới. Giảm mã/xu trước khi xác nhận.');return {spent,returned:oldSpent-spent,earned:stay({total,voucher,spent,tier:Math.max(oldTier,tier)})};}
function sample(){return {today:'2026-09-23',user:'khach.mau@bookese.vn',monthUsed:4900000,lifetime:6,rolling:3,logs:[{id:'GD-001',date:'2026-09-22',type:'Ghi có',source:'LT-1001',amount:12000,before:88000,after:100000,lot:'LO-03',note:'Hoàn tất lưu trú • chính sách PA-C 1%'}],lots:[{id:'LO-01',source:'Giới thiệu • GT-001',credit:'2026-04-01',expiry:'2026-10-01',remaining:50000,status:'Khả dụng'},{id:'LO-02',source:'Lưu trú • LT-0999',credit:'2026-08-20',expiry:'2028-08-20',remaining:38000,status:'Khả dụng'},{id:'LO-03',source:'Lưu trú • LT-1001',credit:'2026-09-22',expiry:'2028-09-22',remaining:12000,status:'Khả dụng'},{id:'LO-04',source:'Lưu trú • LT-1002',credit:'2026-09-26',expiry:'2028-09-26',remaining:8340,status:'Chờ ghi có'}],campaigns:[]};}
function read(user='demo-user-1'){try{const saved=JSON.parse(localStorage.getItem('bookese-loyalty-v1-'+user));if(saved)return saved;const s=sample();s.user=user;const d=JSON.parse(localStorage.getItem('bookese-intranet-ui-v1')||'{}'),b=d.voucherBalances?.[user];if(b!==undefined){s.logs=[{id:'GD-MIGRATE',date:s.today,type:'Ghi có',source:'Số dư bản thử trước',amount:b,before:0,after:b,lot:'LO-MIGRATE',note:'Chuyển số dư mẫu; không phải thưởng mới.'}];s.lots=s.lots.filter(l=>l.status!=='Khả dụng');s.lots.unshift({id:'LO-MIGRATE',source:'Số dư bản thử trước',credit:s.today,expiry:'2028-09-23',remaining:Math.max(0,b),status:'Khả dụng'});}return s}catch{return sample()}}
function write(s,user='demo-user-1'){localStorage.setItem('bookese-loyalty-v1-'+user,JSON.stringify(s));const d=JSON.parse(localStorage.getItem('bookese-intranet-ui-v1')||'{}');d.voucherBalances||={};d.voucherBalances[user]=balance(s);localStorage.setItem('bookese-intranet-ui-v1',JSON.stringify(d));}
function balance(s){return s.lots.filter(l=>l.status==='Khả dụng'&&l.expiry>=s.today).reduce((a,l)=>a+l.remaining,0)-Number(s.debt||0)}
const api={tiers,spendLimit,stay,flight,allocate,refund,amend,sample,read,write,balance};root.BookeseLoyalty=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
