/* Customer pages follow the existing Bookese account and gift navigation. */
(function(){
const O=CoinOps,L=BookeseLoyalty,E=O.html,N=O.number,T=O.table;
const user=()=>loyaltyUser(),state=()=>L.read(user());
let historyTab='Tất cả';
const navItems=[['membership','Thưởng hoàn xu'],['points-history','Lịch sử xu'],['my-gifts','Quà của tôi'],['exchange-gifts','Đổi quà']];
const side=page=>`<nav class="ops-account-nav" aria-label="Tài khoản">${navItems.map(([r,t])=>`<a href="#${r}" class="${page===r?'active':''}">${t}</a>`).join('')}</nav>`;
const shell=(page,body)=>window.bookeseAccountShell?window.bookeseAccountShell(page,body):`<div class="ops-account">${side(page)}<div>${body}</div></div>`;
const login=()=>`<section class="card"><h1>Lịch sử và quyền lợi của bạn</h1><p>Đăng nhập để xem xu và quà của bạn.</p><button class="primary" onclick="loginDemo()">Đăng nhập thử</button></section>`;
const cards=()=>{const p=O.policy();return `<div class="ops-tier-cards">${L.tiers.map((t,i)=>`<article class="${customer.tier===i?'current':''}"><h2>${t}</h2><p>${i===0?'Có tài khoản Bookese':i===1?'Đạt 4 điểm tích lũy':'Đạt 8 điểm trong 12 tháng'}</p><h3>Hoàn ${p.rates[i]}% xu lưu trú</h3><p>Nội địa: ${N(p.flight[i])} xu/chặng<br>Quốc tế: ${N(p.flight[i]*p.international)} xu/chặng</p><small>Xu bay tối đa ${p.flightCap}% phí dịch vụ/chặng.</small><p>${i===1?'Duy trì hạng vĩnh viễn':i===2?'Ân hạn 1 quý; chưa đủ điểm sẽ trở về Thân thiết':''}</p>${customer.tier===i?'<b>Hạng của bạn</b>':''}</article>`).join('')}</div>`;};
function membership(){const s=state(),tier=customer.tier,p=O.policy();return shell('membership',`<section class="ops-hero"><div><h1>Thưởng hoàn xu</h1><p>Thêm quyền lợi cho mỗi hành trình.</p>${tier<0?'<button class="primary" onclick="loginDemo()">Đăng nhập để xem tiến độ</button>':`<h2>${L.tiers[tier]}</h2><p>${s.lifetime} điểm tích lũy · ${s.rolling}/8 điểm trong 12 tháng</p><progress max="8" value="${s.rolling}"></progress><p>${tier===2?'Duy trì 8 điểm trong 12 tháng để giữ hạng.':'Cần thêm '+Math.max(0,(tier===0?4-s.lifetime:8-s.rolling))+' điểm để lên hạng tiếp theo.'}</p>`}</div><div><span>Số dư xu</span><br><strong>${tier<0?'—':N(L.balance(s))}</strong><p><a href="#points-history">Xem lịch sử xu →</a></p></div></section>${cards()}<section class="card"><h2>Cách tích điểm và nhận xu</h2><p>Mỗi đơn lưu trú hoàn tất: 1 điểm. Mỗi chặng bay hoàn tất: 0,5 điểm. Điểm xét hạng khác với xu dùng thanh toán và đổi quà.</p><p>Xu lưu trú tính trên tiền thực trả sau mã giảm giá và xu đã dùng. Xu đơn hàng có hạn 24 tháng từ khi nhận; ngày nhận dự kiến hiển thị trong Lịch sử xu.</p><p>1 xu = 1đ. Xu dùng để thanh toán hoặc đổi quà, không rút tiền hoặc chuyển cho người khác.</p><p>Giá thành viên tại chỗ nghỉ tham gia là ưu đãi riêng, không phải tỷ lệ hoàn xu.</p></section>`);}
window.opsHistoryTab=t=>{historyTab=t;renderCustomer()};
function points(){if(customer.tier<0)return login();const s=state(),rows=O.events(user()).filter(x=>!new URLSearchParams(location.hash.split('?')[1]).get('transaction')||x.id===new URLSearchParams(location.hash.split('?')[1]).get('transaction')).filter(x=>historyTab==='Tất cả'||(historyTab==='Chờ nhận'?x.type==='Xu chờ':historyTab==='Đã nhận'?x.type==='Ghi có':historyTab==='Đã dùng'?['Thanh toán','Đổi quà'].includes(x.type):historyTab==='Hoàn xu'?['Hoàn xu','Thu hồi','Bù xu'].includes(x.type):x.type==='Hết hạn'));return shell('points-history',`<h1>Lịch sử xu</h1>${location.hash.includes('?transaction=')?'<p><a href="#points-history">← Tất cả giao dịch xu</a></p>':''}${O.stats(user())}${O.expiring(s)?`<div class="ops-notice">${N(O.expiring(s))} xu sẽ hết hạn trong 30 ngày. <a href="#exchange-gifts">Xem quà đổi xu</a></div>`:''}<div class="tabs">${['Tất cả','Chờ nhận','Đã nhận','Đã dùng','Hoàn xu','Đã hết hạn'].map(t=>`<button class="${historyTab===t?'active':''}" onclick="opsHistoryTab('${t}')">${t}</button>`).join('')}</div><section class="card">${rows.map(x=>`<details class="ops-history-item"><summary><span><b>${E(x.type)} · ${E(x.source)}</b><small style="display:block">${E(x.date)} · ${E(x.status)}</small></span><b class="${x.amount<0?'ops-minus':'ops-plus'}">${x.amount>0?'+':''}${N(x.amount)} xu</b></summary><p>${E(x.note)}</p><p>Mã giao dịch: ${E(x.id)}</p><p>${x.before===null?'Xu chưa khả dụng. Nhận khi dịch vụ thực tế hoàn tất.':'Số dư: '+N(x.before)+' → '+N(x.after)+' xu'}</p><p>Lô xu: ${E(x.lot)}</p>${s.lots.filter(l=>x.lot.includes(l.id)).map(l=>`<p>Hạn dùng: ${l.expiry} · Còn ${N(l.remaining)} xu</p>`).join('')}</details>`).join('')||'<p>Chưa có giao dịch trong mục này.</p>'}</section><details class="card"><summary>Xu theo hạn sử dụng</summary>${O.lots(s)}</details><p>Còn hạn mức dùng xu thanh toán tháng: <b>${N(Math.max(0,5000000-s.monthUsed))} xu</b>. Đổi quà có giới hạn riêng của từng quà.</p>`);}
const giftData=()=>voucherRead();
function giftCard(g){const d=giftData(),c=d.campaigns.find(c=>c.id===g.campaign),exclusive=g.giftType==='EXCLUSIVE',ok=exclusive?Number(g.stock??g.quantity??0)>0:c&&VC.active(c)&&VC.stock(c)>0;return `<article><div class="ops-gift-art" aria-hidden="true">${g.image?`<img src="${E(g.image)}" alt="">`:"♧"}</div><span class="badge">${exclusive?'Quà độc quyền':c&&VC.type(c)==='BOOKESE'?'Voucher Bookese':'Giftcode đối tác'}</span><h3>${E(g.name)}</h3><p><b>${N(g.price)} xu</b></p><p>${exclusive?'Nhận quà theo hình thức giao nhận đã chọn':c&&VC.type(c)==='BOOKESE'?'Dùng khi thanh toán tại Bookese':'Dùng tại '+E(c?.partner||'đối tác')}</p><a href="#coin-gift?id=${encodeURIComponent(g.id)}">${ok?'Xem quà →':'Xem điều kiện →'}</a></article>`;}

window.opsSampleGifts=()=>{const d=giftData();d.campaigns||=[];d.gifts||=[];const samples=[{id:'coin-demo-bookese',name:'Voucher Bookese mẫu 30.000đ',voucherType:'BOOKESE',issueMode:'exchange',discount:'AMOUNT',value:30000,min:100000,cap:0,quota:20,budget:600000,service:'hotel',status:'Đang chạy',start:'2026-09-01',end:'2027-09-30',expiry:'2027-12-31',issued:[]},{id:'coin-demo-partner',name:'Giftcode ăn uống mẫu',voucherType:'PARTNER',partner:'Nhà hàng minh họa',status:'Đang chạy',start:'2026-09-01',end:'2027-09-30',expiry:'2027-12-31',codes:['DEMO-FOOD-001','DEMO-FOOD-002'],issued:[],terms:'Áp dụng một lần tại nhà hàng minh họa.'}];for(const c of samples){if(!d.campaigns.some(x=>x.id===c.id))d.campaigns.push(c);const id=c.id+'-gift';if(!d.gifts.some(x=>x.id===id))d.gifts.push({id,name:c.name,campaign:c.id,giftType:'VOUCHER',status:'Công khai',price:10000,limit:1,usage:c.voucherType==='BOOKESE'?'Nhập mã khi thanh toán đơn lưu trú từ 100.000đ.':'Xuất trình mã tại nhà hàng minh họa.',terms:'Mỗi tài khoản đổi tối đa 1 lần.'})}localStorage.setItem('bookese-intranet-ui-v1',JSON.stringify(d));renderCustomer()};

function exchangeGifts(){const d=giftData(),gifts=(d.gifts||[]).filter(g=>g.status==='Công khai'),s=state();return `<section class="ops-hero"><div><h1>Tích xu đổi quà mỗi ngày</h1><p>Chọn quà yêu thích từ số xu bạn đã nhận.</p><div class="ops-inline-actions"><a href="#my-gifts">Quà của tôi</a><a href="#points-history">Lịch sử xu</a><a href="#membership">Thưởng hoàn xu</a></div></div><div><span>Số dư xu</span><br><strong>${customer.tier<0?'—':N(L.balance(s))} xu</strong>${customer.tier<0?'<p>Đăng nhập để xem số dư.</p>':`<p>Xu chờ nhận: ${N(s.lots.filter(l=>l.status==='Chờ ghi có').reduce((a,l)=>a+l.remaining,0))}</p><p>${N(O.expiring(s))} xu hết hạn trong 30 ngày</p>`}</div></section>${!gifts.length?'<p class="ops-notice">Dữ liệu bản thử chưa có quà công khai. <button onclick="opsSampleGifts()">Nạp 2 quà mẫu để thử đổi xu</button></p>':''}${[['Quà độc quyền',true],['Quà Voucher',false]].map(([t,ex])=>`<section><h2>${t}</h2><div class="ops-gifts">${gifts.filter(g=>(g.giftType==='EXCLUSIVE')===ex).map(giftCard).join('')||'<p>Chưa có quà đang mở đổi.</p>'}</div></section>`).join('')}`;}
function giftDetail(){const id=new URLSearchParams(location.hash.split('?')[1]).get('id'),d=giftData(),g=d.gifts.find(g=>g.id===id);if(!g)return '<h1>Không tìm thấy quà</h1><a href="#exchange-gifts">Về danh sách quà</a>';const c=d.campaigns.find(c=>c.id===g.campaign),exclusive=g.giftType==='EXCLUSIVE';return `<p><a href="#exchange-gifts">Đổi quà</a> / Chi tiết quà</p><section class="ops-hero"><div class="ops-gift-art">♧</div><div><h1>${E(g.name)}</h1><h2>${N(g.price)} xu</h2><p>Đang có: ${customer.tier<0?'—':N(L.balance(state()))} xu khả dụng</p><p>Hạn sử dụng: ${E(c?.expiry||g.exchangeEnd||'Theo điều kiện quà')}</p><button class="primary" onclick="opsGiftConfirm('${E(g.id)}')">${exclusive?'Đổi quà':'Đổi voucher'}</button></div></section><section class="card"><h2>Cách sử dụng</h2><p>${E(g.usage||g.description||'Xem hướng dẫn khi nhận quà.')}</p><h2>Điều kiện áp dụng</h2><p>${E(g.terms||c?.terms||'Chỉ cấp cho tài khoản đổi quà; không chuyển cho tài khoản khác.')}</p><p>${exclusive?'Quà được xử lý theo trạng thái giao nhận.':c&&VC.type(c)==='BOOKESE'?'Voucher chỉ dùng tại Bookese.':'Giftcode dùng tại '+E(c?.partner||'đối tác')+'; không nhập tại thanh toán Bookese.'}</p></section>`;}
window.opsGiftConfirm=id=>{if(customer.tier<0){loginDemo();return}const d=giftData(),g=d.gifts.find(g=>g.id===id),before=L.balance(state());if(!g)return;modal('Xác nhận đổi quà',`<h3>${E(g.name)}</h3>${T(['Thông tin tóm tắt','Xu'],[['Xu khả dụng',N(before)],['Số lượng','1'],['Giá đổi','−'+N(g.price)],['Còn lại sau khi đổi',N(Math.max(0,before-g.price))]])}<p>Xu chờ chưa được dùng. Hệ thống dùng xu hết hạn sớm trước.</p><label><input type="checkbox" id="opsGiftAgree"> Tôi đã đọc điều kiện sử dụng quà</label><div id="exchangeError" class="error" role="alert"></div><div class="ops-inline-actions"><button onclick="document.querySelector('#detail').close()">Hủy</button><button class="primary" ${before<g.price?'disabled':''} onclick="opsGiftSubmit('${E(id)}',this)">Xác nhận đổi</button></div>${before<g.price?'<p>Không đủ xu khả dụng.</p>':''}`);};
window.opsGiftSubmit=(id,button)=>{if(!$('#opsGiftAgree').checked){$('#exchangeError').textContent='Vui lòng xác nhận đã đọc điều kiện.';return}button.disabled=true;try{O.redeemGift(id,user());$('#detail').close();location.hash='my-gifts';renderCustomer()}catch(err){$('#exchangeError').textContent=err.message;button.disabled=false}};function myGifts(){if(customer.tier<0)return login();const d=giftData(),rows=[...(d.campaigns||[]).flatMap(c=>VC.records(c)),...(d.voucherExchanges||[]).filter(r=>r.voucherType==='EXCLUSIVE')].filter(r=>r.user===user());return shell('my-gifts',`<h1>Quà của tôi</h1><p><a href="#exchange-gifts">Đổi thêm quà</a> · <a href="#points-history">Xem lịch sử xu</a></p>${rows.map(r=>`<section class="card"><div class="row"><h2>${E(r.giftName||r.campaignName)}</h2><span class="badge">${E(r.status)}</span></div>${r.code?`<h3>${E(r.code)}</h3>`:''}<p>${r.voucherType==='EXCLUSIVE'?'Quà đang được xử lý giao nhận':r.voucherType==='BOOKESE'?'Sử dụng tại thanh toán Bookese':'Sử dụng tại '+E(r.partner)}</p>${r.expiry?`<p>Hạn dùng: ${E(r.expiry)}</p>`:''}<p>${r.source==='direct'?'CS cấp bù, không trừ xu':'Đã dùng '+N(r.coins)+' xu để đổi'}</p><p>${E(r.terms)}</p><p>Mã lượt đổi/cấp: ${E(r.id)}</p>${r.coinTransaction?`<a href="#points-history?transaction=${encodeURIComponent(r.coinTransaction)}">Xem giao dịch xu →</a>`:''}</section>`).join('')||'<section class="card">Bạn chưa có quà. Quà nhận được sẽ xuất hiện tại đây sau khi đổi thành công.</section>'}`);}
const previousRender=renderCustomer;
renderCustomer=function(){previousRender();const page=location.hash.slice(1).split('?')[0],pages={'membership':membership,'points-history':points,'exchange-gifts':exchangeGifts,'coin-gift':giftDetail,'my-gifts':myGifts};if(pages[page])$('#app').innerHTML=pages[page]();document.querySelectorAll('a[href="#wallet"]').forEach(a=>a.href=a.textContent.includes('Đổi quà')?'#exchange-gifts':'#membership');};
window.addEventListener('storage',ev=>{if(ev.key?.startsWith('bookese-loyalty')||ev.key==='bookese-intranet-ui-v1'||ev.key==='bookese-coin-policy-v2')renderCustomer()});
renderCustomer();
})();
