/* Type-specific promotion setup. Shared fields stay consistent with Bookese. */
const offerSpecs={
 'Cơ bản':{title:'Tạo ưu đãi cơ bản',intro:'Giảm giá cho các phòng và ngày lưu trú bạn chọn.',heading:'Mức giảm và phạm vi áp dụng',example:'Khách đặt bất kỳ lúc nào trong thời gian nhận đặt; chỉ các đêm hợp lệ được giảm.'},
 'Phút chót':{title:'Lấp phòng trống với ưu đãi phút chót',intro:'Ưu đãi cho khách đặt sát ngày nhận phòng.',heading:'Khách đặt sát ngày đến bao lâu?',example:'Ví dụ: đặt trước tối đa 3 ngày. Nhận phòng ngày 20 thì đơn đặt từ ngày 17 đến ngày 20 đủ điều kiện.'},
 'Đặt sớm':{title:'Thu hút đặt phòng sớm',intro:'Ưu đãi cho khách lên kế hoạch trước chuyến đi.',heading:'Khách cần đặt trước ít nhất bao nhiêu ngày?',example:'Ví dụ: đặt trước tối thiểu 30 ngày. Đơn đặt trước 29 ngày không được áp dụng.'},
 'Dài hạn':{title:'Tạo ưu đãi lưu trú dài hạn',intro:'Ưu đãi theo độ dài kỳ lưu trú của khách.',heading:'Kỳ lưu trú tối thiểu',example:'Ngưỡng xét theo tổng số đêm của kỳ lưu trú. Sau khi đạt ngưỡng, chỉ các đêm hợp lệ trong lịch ưu đãi được giảm.'},
 'Di động':{title:'Tạo giá ưu đãi trên di động',intro:'Tiếp cận khách đặt từ web di động hoặc ứng dụng.',heading:'Khách đặt trên kênh nào?',example:'Kênh được xác minh tại checkout. Không xác định kênh thì không áp ưu đãi di động; không dùng độ rộng màn hình làm điều kiện.'},
 'Package':{title:'Tạo ưu đãi combo du lịch',intro:'Cấu hình cho sản phẩm Combo riêng hoặc cross-sell từ vé máy bay. Sản phẩm này triển khai giai đoạn sau; không áp cho phòng lẻ.',heading:'Combo nào được hưởng ưu đãi?',example:'Chỉ áp dụng phần tiền phòng của combo đủ điều kiện. Đặt phòng riêng không được hưởng; không cộng ưu đãi di động trong cùng nhóm.'},
 'Thứ hạng':{title:'Đăng ký ưu đãi Thứ hạng',intro:'Cam kết giá tốt nhất để Bookese xét quảng bá tại top thị trường trong một giai đoạn.',heading:'Thời gian cam kết giá và quảng bá',example:'Tối đa 72 giờ/đợt; mỗi chỗ nghỉ một đợt trong chu kỳ 14 ngày. Vị trí cụ thể và thời gian quảng bá phải được Bookese xác nhận.'},
 'Flash Sale':{title:'Tạo đợt Flash Sale',intro:'Đợt mở bán theo giờ để thúc đẩy đặt phòng; không kèm cam kết vị trí top như Ưu đãi Thứ hạng.',heading:'Thời gian mở bán Flash Sale',example:'Chỉ đơn đặt trong khung giờ mở bán và đêm lưu trú hợp lệ mới được xét. Hết giờ tự dừng. Có thể quảng bá trong một chiến dịch nhưng không cộng thêm lớp giảm chiến dịch. Không đồng nghĩa đặt sát ngày nhận phòng.'},
 'Đợt giảm sâu đặc biệt':{title:'Tạo đợt giảm sâu đặc biệt',intro:'Thiết lập chương trình giảm sâu theo lịch của chỗ nghỉ.',heading:'Lịch chương trình đặc biệt',example:'Loại cũ chỉ giữ để tra cứu. Chuyển sang Flash Sale khi sửa chương trình để tránh trùng loại.'}
};
function offerInput(label,name,type,value,attrs=''){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value??'')}" ${attrs}></label>`}
edit=function(id,g='condition',t='Cơ bản'){const p=id?data.items.find(x=>x.id===id):null;if(g==='member'){targetGo('member');return}if(g==='campaign'||p?.group==='campaign'){targetGo('campaigns');return}editing=id;formGroup=p?.group||g;formType=(p?.type||t)==='Đợt giảm sâu đặc biệt'?'Flash Sale':(p?.type||t);targetView='form';targetRender()};
renderBookeseForm=function(){const p=data.items.find(x=>x.id===editing)||{},spec=offerSpecs[formType]||offerSpecs['Cơ bản'],exclusive=formGroup==='exclusive',timed=['Thứ hạng','Flash Sale'].includes(formType),thresholdLabel={'Phút chót':'Đặt trước tối đa (ngày)','Đặt sớm':'Đặt trước tối thiểu (ngày)','Dài hạn':'Số đêm lưu trú tối thiểu'}[formType];
 let special='';
 if(thresholdLabel)special=offerInput(thresholdLabel,'threshold','number',p.threshold??({'Phút chót':3,'Đặt sớm':30,'Dài hạn':7}[formType]),`required min="${formType==='Phút chót'?0:1}" max="365" step="1"`);
 if(formType==='Di động')special=`<div class="channel-options">${[['both','Web di động và ứng dụng','Áp dụng trên cả hai kênh'],['web-mobile','Chỉ web di động','Khách đặt trên trình duyệt điện thoại'],['app','Chỉ ứng dụng','Khách đặt qua ứng dụng Bookese']].map(([v,n,d])=>`<label class="channel-choice"><input type="radio" name="channel" value="${v}" ${(p.channel||'both')===v?'checked':''}><span><b>${n}</b><small>${d}</small></span></label>`).join('')}</div>`;
 if(timed)special=`<div class="formgrid">${offerInput('Bắt đầu nhận đặt (giờ Việt Nam)','boostStart','datetime-local',p.boostStart,'required')}${offerInput('Kết thúc nhận đặt (giờ Việt Nam)','boostEnd','datetime-local',p.boostEnd,'required')}</div>`;
 if(formType==='Đợt giảm sâu đặc biệt')special=`<div class="formgrid">${offerInput('Nhận đặt từ','start','date',p.start,'required')}${offerInput('Nhận đặt đến','end','date',p.end,'required')}</div>`;
 if(formType==='Package')special=`<label class="field">Loại combo<select name="packageKind"><option value="flight" ${p.packageKind==='flight'?'selected':''}>Khách sạn + vé máy bay</option><option value="travel" ${p.packageKind==='travel'?'selected':''}>Khách sạn + dịch vụ du lịch</option></select></label><label class="field">Combo do Bookese cung cấp<select name="packageId" required><option value="">Chọn combo</option><option value="DANANG-FLIGHT" ${p.packageId==='DANANG-FLIGHT'?'selected':''}>DANANG-FLIGHT · Khách sạn + vé máy bay</option><option value="DANANG-TOUR" ${p.packageId==='DANANG-TOUR'?'selected':''}>DANANG-TOUR · Khách sạn + dịch vụ du lịch</option></select></label><p class="muted">Mã demo ví dụ: DANANG-FLIGHT hoặc DANANG-TOUR. Triển khai thật chọn từ danh mục combo đang mở của Bookese.</p>`;
 const scope=roomScopeFields(p);
 const discount=offerInput('Mức giảm (%)','rate','number',p.rate??10,'required min="1" max="99" step="1"');
 $('#content').innerHTML=`<div class="offer-layout"><form id="typeOffer"><section class="bookese-panel"><button type="button" class="quiet" onclick="targetGo('catalog')">← Chọn loại ưu đãi khác</button><h2 style="margin-top:12px">${editing?'Chỉnh sửa · '+formType:spec.title}</h2><p class="muted">${spec.intro}</p></section><section class="bookese-panel"><h2>${spec.heading}</h2>${special}${formType==='Cơ bản'?discount+scope:''}<p class="note">${spec.example}</p>${formType==='Thứ hạng'?'<div class="note">Quyền lợi: vị trí top thị trường trong thời gian Bookese duyệt, kèm nhãn ưu đãi. Flash Sale chỉ có giá bán nhanh và thời hạn, không mặc định có quyền lợi top thị trường. Mức giảm tối thiểu theo khung chương trình, không tự cam kết một mức cố định.</div>':''}</section>${formType!=='Cơ bản'?`<section class="bookese-panel"><h2>${formType==='Dài hạn'?'Giảm giá cho kỳ lưu trú dài':'Mức giảm và phòng tham gia'}</h2>${discount}${scope}</section>`:''}<section class="bookese-panel"><h2>${timed||formType==='Đợt giảm sâu đặc biệt'?'Lịch lưu trú được hưởng ưu đãi':'Thời gian áp dụng'}</h2>${!timed&&formType!=='Đợt giảm sâu đặc biệt'?`<div class="formgrid">${offerInput('Nhận đặt từ','start','date',p.start,'required')}${offerInput('Nhận đặt đến','end','date',p.end,'required')}</div>`:''}<div class="formgrid">${offerInput('Lưu trú từ','stayStart','date',p.stayStart,'required')}${offerInput('Lưu trú đến','stayEnd','date',p.stayEnd,'required')}</div><div class="weekday">${['CN','T2','T3','T4','T5','T6','T7'].map((n,i)=>`<label><input type="checkbox" name="weekday" value="${i}" ${(p.weekdays||[0,1,2,3,4,5,6]).includes(i)?'checked':''}> ${n}</label>`).join('')}</div><label class="field">Cách áp lịch lưu trú<select name="wholeStay"><option value="false">Giảm từng đêm đủ điều kiện</option></select></label>${offerInput('Ngày loại trừ (YYYY-MM-DD, cách nhau bằng dấu phẩy)','excludedDates','text',(p.excluded||[]).join(', '))}</section><section class="bookese-panel"><h2>Tên khuyến mãi nội bộ</h2>${offerInput('Tên khuyến mãi','name','text',p.name||'', 'required maxlength="100"')}<p class="muted">Chỉ dùng để quản lý tại chỗ nghỉ.</p><div id="formerror" class="error" role="alert"></div><div class="actions"><button type="button" onclick="targetGo('catalog')">Hủy</button><button class="primary">${editing?'Lưu thay đổi':formType==='Thứ hạng'?'Lưu đợt Thứ hạng':'Tạo ưu đãi'}</button></div></section></form><aside class="offer-summary bookese-panel"><h2>${formType}</h2><div id="offerSummary"></div><hr><h3>Quy tắc kết hợp</h3><p>${exclusive?'Nhánh A · Ưu đãi độc quyền. Không cộng với ưu đãi chỗ nghỉ khác hoặc giá thành viên.':'Nhánh C · Một ưu đãi điều kiện + một ưu đãi theo kênh / combo + giá thành viên.'}</p><p>Mã Bookese và xu áp tiếp tại checkout. Mỗi đêm phải đạt sàn của chỗ nghỉ.</p><p class="muted">Sửa hoặc tạm ngưng chỉ áp dụng đơn mới. Đơn đã xác nhận giữ quyền lợi.</p></aside></div>`;
 $('#typeOffer').oninput=typeOfferPreview;$('#typeOffer').onsubmit=saveTypeOffer;typeOfferPreview();
};
function typeOfferPreview(){const f=$('#typeOffer'),s=Object.fromEntries(new FormData(f));let detail=formType==='Phút chót'?`Khách đặt trước tối đa ${s.threshold||'…'} ngày`:formType==='Đặt sớm'?`Khách đặt trước tối thiểu ${s.threshold||'…'} ngày`:formType==='Dài hạn'?`Khách lưu trú từ ${s.threshold||'…'} đêm`:formType==='Di động'?{both:'Web di động và ứng dụng',app:'Chỉ ứng dụng','web-mobile':'Chỉ web di động'}[s.channel]:formType==='Package'?`${s.packageId||'Chưa chọn combo'} · Chỉ giảm phần phòng`:['Thứ hạng','Flash Sale'].includes(formType)?`${s.boostStart||'Chưa chọn giờ bắt đầu'} → ${s.boostEnd||'Chưa chọn giờ kết thúc'}`:'Theo lịch và phòng đã chọn';$('#offerSummary').innerHTML=`<p><b style="font-size:28px;color:#008bad">${eSafe(s.rate||0)}%</b> giảm giá</p><p>${eSafe(detail)}</p><p class="muted">${s.wholeStay==='true'?'Yêu cầu toàn bộ kỳ lưu trú hợp lệ':'Xét theo từng đêm hợp lệ'}</p>`}
function eSafe(x){return esc(String(x))}
function saveTypeOffer(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target)),err=m=>$('#formerror').textContent=m,timed=['Thứ hạng','Flash Sale'].includes(formType);f.roomRates=new FormData(ev.target).getAll('roomRates');if(!f.roomRates.length)return err('Chọn ít nhất một phòng × loại giá.');f.room='selected';if(formType==='Package'&&((f.packageKind==='flight'&&f.packageId!=='DANANG-FLIGHT')||(f.packageKind==='travel'&&f.packageId!=='DANANG-TOUR')))return err('Loại combo phải khớp với combo Bookese đã chọn.');if(timed){f.start=f.boostStart.slice(0,10);f.end=f.boostEnd.slice(0,10);const a=Date.parse(f.boostStart+'+07:00'),b=Date.parse(f.boostEnd+'+07:00');if(!(b>a))return err('Giờ kết thúc phải sau giờ bắt đầu.');if(formType==='Thứ hạng'){if(b-a>72*3600000)return err('Đợt Thứ hạng không vượt 72 giờ.');if(data.items.some(x=>x.id!==editing&&x.type==='Thứ hạng'&&x.boostStart&&Math.abs(a-Date.parse(x.boostStart+'+07:00'))<14*86400000))return err('Đã có đợt Thứ hạng trong chu kỳ 14 ngày.')}}if(f.end<f.start||f.stayEnd<f.stayStart)return err('Ngày kết thúc phải bằng hoặc sau ngày bắt đầu.');const weekdays=new FormData(ev.target).getAll('weekday').map(Number),excluded=f.excludedDates.split(',').map(x=>x.trim()).filter(Boolean);if(!weekdays.length)return err('Chọn ít nhất một ngày trong tuần.');if(excluded.some(x=>!/^\d{4}-\d{2}-\d{2}$/.test(x)||isNaN(Date.parse(x))))return err('Ngày loại trừ cần theo YYYY-MM-DD.');const prior=data.items.find(x=>x.id===editing)||{},p={...prior,...f,id:editing||Date.now(),group:formGroup,type:formType,rate:+f.rate,threshold:+(f.threshold||0),wholeStay:false,weekdays,excluded,status:prior.status||'active'};if(editing)data.items=data.items.map(x=>x.id===editing?p:x);else data.items.push(p);targetView='list';history.replaceState(null,'','#list');persist(`${editing?'Sửa':'Tạo'} ${formType}: ${p.name}`)}
document.head.insertAdjacentHTML('beforeend',`<style>.offer-layout{display:grid;grid-template-columns:minmax(0,800px) minmax(240px,320px);gap:24px;align-items:start}.offer-layout section{margin-bottom:20px}.offer-summary{position:sticky;top:20px;font-size:13px}.offer-summary hr{border:0;border-top:1px solid #e6ebf2;margin:22px 0}.channel-options{display:grid;gap:12px;margin-top:20px}.channel-choice{display:flex;gap:14px;padding:16px;border:1px solid #dde5ed;cursor:pointer;align-items:center}.channel-choice:has(input:checked){border-color:#00b9ed;background:#f1fbfe}.channel-choice small{display:block;margin-top:5px;color:#718099}.channel-choice input{accent-color:#00b9ed}.offer-layout .weekday{display:flex;gap:14px;flex-wrap:wrap;margin:20px 0}@media(max-width:1050px){.offer-layout{grid-template-columns:1fr}.offer-summary{position:static}}</style>`);
document.head.insertAdjacentHTML('beforeend','<style>.sidebar .logo::first-letter{font-size:inherit}</style>');
