/* Shared demo records: one marketing program -> price offers + voucher campaigns. */
const flightMarketingSample={id:'flight-marketing-demo',name:'Vé máy bay mùa thu · ví dụ',start:'2026-09-01',end:'2026-12-31',owner:'Marketing Bookese',status:'Nháp',description:'Ví dụ đợt tiếp thị riêng cho vé máy bay.',serviceType:'flight',flightConditions:{scope:'domestic',discountType:'amount',discount:50000,minimum:0,maximum:null}};
window.BookeseTarget={
 key:'bookese-target-product-v1',
 read(){try{const x=JSON.parse(localStorage.getItem(this.key));if(x){for(const r of x.registrations||[]){if(['Bookese dừng','Từ chối'].includes(r.status))r.adminStopped=true;const p=x.prices.find(p=>p.id===r.price),g=x.programs.find(g=>g.id===p?.program);const extras=r.extras||[];if(r.status==='Chờ duyệt'&&!r.adminStopped&&p?.status==='Đang mở'&&g?.status==='Đang mở'&&Number(r.rate)>=Number(p.min)&&Number(r.rate)<100&&r.roomRates?.length&&(!g.markets?.length||g.markets.includes('Đà Nẵng'))&&(!p.benefitRequired||extras.length)&&extras.every(e=>e.description?.trim())){r.status='Đã tham gia';r.confirmedBy='Tự động xác nhận';r.reviewedAt=new Date().toISOString()}}if(!x.programs.some(p=>p.id===flightMarketingSample.id))x.programs.push({...flightMarketingSample});return x}}catch{}return {programs:[{id:'summer',name:'Kỳ nghỉ mùa thu 2026',start:'2026-09-01',end:'2026-12-31',owner:'Marketing Bookese',status:'Đang mở',description:'Thúc đẩy đặt phòng mùa thu tại các chỗ nghỉ tham gia.',serviceType:'stay'},{...flightMarketingSample}],prices:[{id:'autumn-price',program:'summer',name:'Ưu đãi lưu trú mùa thu',start:'2026-09-01',end:'2026-12-31',stayStart:'2026-09-01',stayEnd:'2026-12-31',min:15,approvalRequired:false,placement:'Nhãn ưu đãi mùa thu và trang chiến dịch',limited:false,status:'Đang mở'}],registrations:[],member:{tier1:true,tier2:true,plans:{deluxe:2,suite:1},excluded:[]},maxDiscount:35,logs:[]}},
 write(d,message){d.logs.unshift({at:new Date().toLocaleString('vi-VN'),message});localStorage.setItem(this.key,JSON.stringify(d));window.dispatchEvent(new Event('bookese-change'))},
 update(fn,message){let d=this.read();fn(d);this.write(d,message)},
 esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
};
