/* Shared demo records: one marketing program -> price offers + voucher campaigns. */
const flightMarketingSample={id:'flight-marketing-demo',name:'Vé máy bay mùa thu · ví dụ',start:'2026-09-01',end:'2026-12-31',owner:'Marketing Bookese',status:'Nháp',description:'Ví dụ đợt tiếp thị riêng cho vé máy bay.',serviceType:'flight',flightConditions:{scope:'domestic',discountType:'amount',discount:50000,minimum:0,maximum:null}};
window.BookeseTarget={
 key:'bookese-target-product-v1',
 read(){try{const x=JSON.parse(localStorage.getItem(this.key));if(x){for(const r of x.registrations||[]){if(r.confirmedBy==='Tự xác nhận'){r.status='Chờ duyệt';r.confirmedBy=null;r.reviewedAt=null}}if(!x.programs.some(p=>p.id===flightMarketingSample.id))x.programs.push({...flightMarketingSample});return x}}catch{}return {programs:[{id:'summer',name:'Kỳ nghỉ mùa thu 2026',start:'2026-09-01',end:'2026-12-31',owner:'Marketing Bookese',status:'Đang mở',description:'Thúc đẩy đặt phòng mùa thu tại các chỗ nghỉ tham gia.',serviceType:'stay'},{...flightMarketingSample}],prices:[{id:'autumn-price',program:'summer',name:'Ưu đãi lưu trú mùa thu',start:'2026-09-01',end:'2026-12-31',stayStart:'2026-09-01',stayEnd:'2026-12-31',min:15,approvalRequired:true,placement:'Nhãn ưu đãi mùa thu và trang chiến dịch',limited:false,status:'Đang mở'}],registrations:[],member:{tier1:true,tier2:true,plans:{deluxe:2,suite:1},excluded:[]},maxDiscount:35,logs:[]}},
 write(d,message){d.logs.unshift({at:new Date().toLocaleString('vi-VN'),message});localStorage.setItem(this.key,JSON.stringify(d));window.dispatchEvent(new Event('bookese-change'))},
 update(fn,message){let d=this.read();fn(d);this.write(d,message)},
 esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
};
