/* PARTNER codes are stocked before exchange; BOOKESE is issued on demand. */
const sourceCampaignForm=campaignForm,sourceGiftForm=giftForm;
campaignForm=function(){sourceCampaignForm();const f=$('#cf'),c=db.campaigns.find(x=>x.id===editing)||{},box=$('#partnerBox');if(!box)return;
 box.insertAdjacentHTML('afterbegin',`${select('Nguồn giftcode','codeSource',[['supplier','Khách sạn cung cấp'],['generated','Bookese sinh mã']],c.codeSource||'supplier')}<div id="generatedFormat"><div class="fields">${field('Tiền tố mã','codePrefix','text',c.codePrefix||'KS','maxlength="10" pattern="[A-Za-z0-9]{2,10}"')}${field('Số ký tự ngẫu nhiên sau tiền tố','codeLength','number',c.codeLength||8,'min="6" max="16"')}</div><p class="muted">Mã gồm tiền tố + chuỗi chữ/số ngẫu nhiên, không có dấu cách. Số lượng nhập khi tạo lô trong Kho mã.</p><label><input type="checkbox" name="partnerAgreed" ${c.partnerAgreed?'checked':''}> Khách sạn đã đồng ý tiếp nhận mã do Bookese sinh theo định dạng này.</label></div><p id="codeSourceHelp" class="hint"></p>`);
 const prior=f.onchange;function update(){const partner=f.voucherType.value==='PARTNER',generated=partner&&f.codeSource.value==='generated';f.codeSource.disabled=!partner;$('#generatedFormat').hidden=!generated;for(const key of ['codePrefix','codeLength','partnerAgreed']){f.elements[key].disabled=!generated;f.elements[key].required=generated;}$('#codeSourceHelp').textContent=generated?'Lưu cấu hình → Tạo lô giftcode → duyệt/phát hành → liên kết quà đổi xu. Khi khách đổi, lấy một mã chưa cấp trong kho.':'Lưu cấu hình → Nhập giftcode khách sạn cung cấp → duyệt/phát hành → liên kết quà đổi xu. Số lượng kho bằng số mã hợp lệ đã nhập.';}
 f.onchange=ev=>{prior?.(ev);update()};f.querySelectorAll('[data-kind]').forEach(b=>{const old=b.onclick;b.onclick=()=>{old();update()}});update();
 const codes=document.querySelector('section[data-panel="codes"]');if(codes&&VM.type(c)==='PARTNER'){const b=codes.querySelector('button[onclick="codeBatch()"]');if(b)b.textContent=c.codeSource==='generated'?'＋ Tạo lô giftcode':'＋ Nhập giftcode';codes.querySelector('.row').insertAdjacentHTML('afterend',`<p class="muted">Nguồn: ${c.codeSource==='generated'?'Bookese sinh mã':'Khách sạn cung cấp'} · Tổng ${c.codes?.length||0} mã · Chưa cấp ${VM.stock(c)} · Đã cấp ${VM.records(c).length}</p>`);}
};
codeBatch=function(){const c=db.campaigns.find(x=>x.id===editing);if(VM.type(c)!=='PARTNER')return;const generated=c.codeSource==='generated';if(generated&&(!c.partnerAgreed||!c.codePrefix||!c.codeLength))return toast('Lưu định dạng mã và xác nhận đồng ý của khách sạn trước khi tạo lô.');
 modal(generated?'Tạo lô giftcode':'Nhập giftcode khách sạn cung cấp',`<form id="stockForm">${generated?`<p>Định dạng: <b>${e(c.codePrefix.toUpperCase())} + ${Number(c.codeLength)} ký tự ngẫu nhiên</b></p>${field('Số lượng mã cần tạo','quantity','number',10,'min="1" max="1000" required')}<p class="muted">Tạo sẵn vào kho với trạng thái Chưa cấp. Chưa gắn tài khoản, chưa trừ xu.</p>`:'<label class="field">Danh sách mã<textarea name="codes" rows="8" required placeholder="Mỗi dòng một mã"></textarea></label><p id="stockCount" class="muted">0 mã đã nhập</p>'}<div class="error" id="stockError" role="alert"></div><div class="actions"><button type="button" onclick="closeModal()">Hủy</button><button class="primary">${generated?'Tạo lô mã':'Kiểm tra và nhập mã'}</button></div></form>`);
 const f=$('#stockForm');if(!generated)f.codes.oninput=()=>$('#stockCount').textContent=f.codes.value.split(/\r?\n/).filter(x=>x.trim()).length+' mã đã nhập';f.onsubmit=ev=>{ev.preventDefault();const all=new Set(db.campaigns.flatMap(x=>[...(x.codes||[]),...VM.records(x).map(r=>r.code)]));let list=[];if(generated){const n=+f.quantity.value,len=+c.codeLength;if(!Number.isInteger(n)||n<1||n>1000||len<6||len>16)return $('#stockError').textContent='Số lượng từ 1–1.000; độ dài chuỗi ngẫu nhiên từ 6–16.';while(list.length<n){const code=c.codePrefix.toUpperCase()+crypto.randomUUID().replaceAll('-','').slice(0,len).toUpperCase();if(!all.has(code)){list.push(code);all.add(code)}}}else{list=f.codes.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!list.length||list.some((x,i)=>/\s/.test(x)||list.indexOf(x)!==i||all.has(x)))return $('#stockError').textContent='Có mã trùng, mã đã tồn tại hoặc chứa khoảng trắng. Chưa nhập mã nào; hãy sửa danh sách.';}
 c.codes=[...(c.codes||[]),...list];c.codeOrigins||={};const at=new Date().toISOString(),batch=crypto.randomUUID();list.forEach(code=>c.codeOrigins[code]={source:generated?'generated':'supplier',at,batch});save((generated?'Sinh':'Nhập')+' '+list.length+' giftcode cho '+c.name);closeModal();voucherPanel='codes';campaignForm();};
};
const sourceCodeTable=voucherCodeTable;
voucherCodeTable=function(c){if(VM.type(c)!=='PARTNER')return sourceCodeTable(c);const records=VM.records(c);return `<div class="table"><table><thead><tr><th>Mã</th><th>Nguồn mã</th><th>Ngày nhập / sinh</th><th>Tài khoản nhận</th><th>Ngày cấp</th><th>Hạn dùng</th><th>Cấp mã / Sử dụng</th></tr></thead><tbody>${(c.codes||[]).map(code=>{const r=records.find(x=>x.code===code),o=c.codeOrigins?.[code];return `<tr><td>${e(code)}</td><td>${o?.source==='generated'?'Bookese sinh':'Khách sạn cung cấp'}</td><td>${voucherDate(o?.at)}</td><td>${e(r?.user||'—')}</td><td>${voucherDate(r?.at)}</td><td>${voucherDate(r?.expiry||c.expiry)}</td><td>${r?'Đã cấp · '+e(r.status):'Chưa cấp'}</td></tr>`}).join('')||'<tr><td colspan="7">Kho chưa có mã. Nhập hoặc tạo lô giftcode trước khi phát hành.</td></tr>'}</tbody></table></div>`};
giftForm=function(){sourceGiftForm();const f=$('#gf'),link=$('#giftLink');link.insertAdjacentHTML('beforeend','<p class="hint" id="giftProgramLink"></p>');const prior=f.onchange;function update(){const c=db.campaigns.find(x=>x.id===f.campaign.value),p=c&&T.read().programs.find(x=>x.id===c.program);$('#giftProgramLink').innerHTML=c?(p?`Thuộc đợt tiếp thị: <b>${e(p.name)}</b><br><small>Kế thừa từ chiến dịch voucher đã chọn.</small>`:'<b>Không liên kết đợt tiếp thị</b><br><small>Quà chạy độc lập theo chiến dịch voucher.</small>'):'Đợt tiếp thị sẽ hiển thị sau khi chọn chiến dịch voucher.';}f.onchange=ev=>{prior?.(ev);update()};update();};
const partnerCodesTable=voucherCodeTable;
voucherCodeTable=function(c){if(VM.type(c)!=='BOOKESE')return partnerCodesTable(c);const rows=VM.records(c);return `<p class="muted">Hạn mức ${c.quota||0} mã · Đã cấp ${rows.length} · Còn được cấp ${VM.stock(c)}</p><div class="table"><table><thead><tr><th>Mã</th><th>Tài khoản nhận</th><th>Nguồn cấp / lý do</th><th>Ngày cấp</th><th>Hạn dùng</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.code)}</td><td>${e(r.user)}</td><td>${r.source==='direct'?'CS cấp bù':'Đổi xu'}<br>${e(r.reason)}</td><td>${voucherDate(r.at)}</td><td>${voucherDate(r.expiry)}</td><td>${e(r.status)}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có mã được cấp. Hệ thống sinh mã khi đổi xu hoặc cấp bù thành công.</td></tr>'}</tbody></table></div>`};
const finalSourceForm=campaignForm;
campaignForm=function(){finalSourceForm();const hint=$('#partnerBox > p:last-child');if(hint&&hint.id!=='codeSourceHelp')hint.remove();if($('#cf').voucherType.value==='PARTNER')$('#voucherGuideText').textContent='Lưu cấu hình, nhập hoặc tạo lô mã trong Kho mã, rồi phát hành và liên kết quà đổi xu.';};
nav();
