/* Layout grounded in Bookese's voucher list and gift create/list screens. */
const voucherBaseForm=campaignForm;
let voucherStatusFilter='',voucherPage=1,voucherPanel='config',giftTypeFilter='',giftPage=1;
const voucherDate=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const voucherNum=v=>Number(v||0).toLocaleString('vi-VN');
const voucherBadge=s=>`<span class="status-pill ${['Đang chạy','Công khai'].includes(s)?'live':['Chờ duyệt','Đã duyệt'].includes(s)?'pending':['Từ chối','Tạm ngưng','Hết hạn'].includes(s)?'stopped':''}">${e(s||'Nháp')}</span>`;
function voucherPager(total,page,handler){const pages=Math.max(1,Math.ceil(total/10));return `<div class="list-footer"><span>${total?'Hiển thị '+((page-1)*10+1)+'–'+Math.min(page*10,total)+' / '+total:'0'} kết quả</span><div><button ${page<=1?'disabled':''} onclick="${handler}(${page-1})" aria-label="Trang trước">‹</button> <span>Trang ${page} / ${pages}</span> <button ${page>=pages?'disabled':''} onclick="${handler}(${page+1})" aria-label="Trang sau">›</button></div></div>`}
voucherOpen=function(id){editing=id;voucherPanel='config';location.hash='campaign';campaignForm()};
campaigns=function(){
 $('#app').innerHTML=title('Quản lý chiến dịch voucher','Quà tặng / Quản lý chiến dịch voucher')+`<section class="card"><form id="voucherSearch" class="voucher-toolbar">${field('Tìm kiếm','q','search',query,'placeholder="Tìm tên chiến dịch hoặc mã voucher"')}${select('Trạng thái','state',[['','Tất cả'],...['Nháp','Chờ duyệt','Đã duyệt','Đang chạy','Tạm ngưng','Từ chối'].map(x=>[x,x])],voucherStatusFilter)}<button type="button" onclick="query='';voucherStatusFilter='';typeFilter='';voucherPage=1;campaigns()">Nhập lại</button><button class="primary">Tìm kiếm</button></form></section><section class="card"><div class="row"><div><h2>Danh sách chiến dịch voucher</h2><p class="voucher-subtitle">Quản lý mã công khai, mã cá nhân và giftcode đối tác.</p></div><button class="orange" onclick="voucherOpen(null)">＋ Thêm chiến dịch</button></div><nav class="tabs voucher-tabs" aria-label="Loại voucher">${[['','Tất cả'],['BOOKESE_PUBLIC','BOOKESE_PUBLIC'],['BOOKESE','BOOKESE'],['PARTNER','PARTNER']].map(([v,l])=>`<button class="${typeFilter===v?'active':''}" aria-pressed="${typeFilter===v}" onclick="typeFilter='${v}';voucherPage=1;campaigns()">${l}</button>`).join('')}</nav><div id="campaignRows"></div></section><details class="sample-controls"><summary>Dữ liệu minh họa cho bản thử</summary><button onclick="voucherSamples()">Tạo ví dụ BOOKESE / CS / PARTNER</button></details>`;
 $('#voucherSearch').onsubmit=ev=>{ev.preventDefault();query=ev.target.q.value.trim();voucherStatusFilter=ev.target.state.value;voucherPage=1;campaignRows()};campaignRows();
};
campaignRows=function(){const rows=db.campaigns.filter(c=>(!typeFilter||VM.type(c)===typeFilter)&&(!voucherStatusFilter||c.status===voucherStatusFilter)&&[c.name,c.code,...(c.codes||[]),...VM.records(c).map(r=>r.code)].join(' ').toLowerCase().includes(query.toLowerCase()));voucherPage=Math.min(voucherPage,Math.max(1,Math.ceil(rows.length/10)));$('#campaignRows').innerHTML=`<p class="muted" role="status">${rows.length} chiến dịch</p><div class="table"><table class="voucher-table"><thead><tr><th>Chiến dịch / mã</th><th>Loại voucher</th><th>Thời gian</th><th>Hạn mức / đã cấp</th><th>Đã sử dụng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${rows.slice((voucherPage-1)*10,voucherPage*10).map(c=>{const t=VM.type(c),p=T.read().programs.find(p=>p.id===c.program);return `<tr><td class="name"><button onclick="voucherOpen('${c.id}')">${e(c.name)}</button><small>${t==='BOOKESE_PUBLIC'?e(c.code||'Chưa đặt mã'):t==='BOOKESE'?(c.issueMode==='direct'?'Cấp bù cho tài khoản':'Đổi xu nhận mã cá nhân'):e(c.partner||'Giftcode đối tác')}</small>${p?`<small>Đợt: ${e(p.name)}</small>`:''}</td><td>${t}</td><td>${voucherDate(c.start)} → ${c.end?voucherDate(c.end):'Không giới hạn'}<small>Hạn voucher: ${voucherDate(c.expiry||c.end)}</small></td><td>${voucherNum(t==='PARTNER'?(c.codes||[]).length:c.quota)}${t==='BOOKESE_PUBLIC'?' lượt':` / ${VM.records(c).length} mã`}</td><td>${voucherNum(c.used||VM.records(c).filter(r=>r.status==='Đã sử dụng').length)}</td><td>${voucherBadge(c.status)}</td><td><button onclick="voucherOpen('${c.id}')">Chi tiết</button></td></tr>`}).join('')||'<tr><td colspan="7"><div class="voucher-empty"><b>Không có chiến dịch phù hợp</b><p>Thử thay đổi từ khóa hoặc bộ lọc.</p></div></td></tr>'}</tbody></table></div>${voucherPager(rows.length,voucherPage,'voucherGoPage')}`};
function voucherGoPage(p){voucherPage=p;campaignRows()}
campaignForm=function(){
 voucherBaseForm();const f=$('#cf'),c=db.campaigns.find(x=>x.id===editing),topCards=[...f.querySelectorAll(':scope > section')];
 $('#app').classList.add('voucher-workspace');f.elements.namedItem('name').closest('label').style.gridColumn='1 / -1';if(c)f.voucherType.closest('label').hidden=true;
 const layout=document.createElement('div');layout.className='voucher-config';f.before(layout);layout.append(f);
 topCards.forEach((s,i)=>s.id=s.id||'voucherConfig'+i);
 const guide=document.createElement('section');guide.className='card voucher-guide';guide.innerHTML='<h2>Cấu hình chiến dịch</h2><a href="#" data-jump="0">01　Thông tin & thời gian</a><a href="#" data-jump="1">02　Giá trị & điều kiện</a><a href="#" data-jump="2">03　Mã & hình thức cấp</a><h3 id="voucherGuideTitle"></h3><p id="voucherGuideText"></p>';layout.append(guide);guide.querySelectorAll('[data-jump]').forEach(a=>a.onclick=ev=>{ev.preventDefault();topCards[+a.dataset.jump].scrollIntoView({behavior:'smooth',block:'start'})});
 if(!c){const typeLabel=f.voucherType.closest('label');typeLabel.hidden=true;const chooser=document.createElement('div');chooser.className='voucher-type-cards';chooser.innerHTML=[['BOOKESE_PUBLIC','Mã công khai','Khách nhập mã tại thanh toán.'],['BOOKESE','Mã cá nhân','Đổi xu nhận mã hoặc CS cấp bù.'],['PARTNER','Giftcode đối tác','Nhập mã để đổi quà, dùng tại đối tác.']].map(([t,name,help])=>`<button type="button" data-kind="${t}"><b>${t}</b>${name}<small>${help}</small></button>`).join('');topCards[0].querySelector('.fields').before(chooser);chooser.querySelectorAll('button').forEach(b=>b.onclick=()=>{f.voucherType.value=b.dataset.kind;voucherFields();updateVoucherGuide()});}
 const change=f.onchange;f.onchange=ev=>{change?.(ev);updateVoucherGuide()};updateVoucherGuide();
 if(c){
 const extras=[...$('#app').querySelectorAll(':scope > section')],approval=extras[0],codes=extras[1];
 const head=document.createElement('section');head.className='card voucher-summary';head.innerHTML=`<div><span class="badge">${VM.type(c)}</span> ${voucherBadge(c.status)}<h2>${e(c.name)}</h2><p class="muted">${e(c.owner||'Chưa có người phụ trách')} · ${c.program?'Có liên kết đợt tiếp thị':'Chiến dịch độc lập'}</p><div class="voucher-meta"><span>Thời gian<b>${voucherDate(c.start)} → ${c.end?voucherDate(c.end):'Không giới hạn'}</b></span><span>Hạn voucher<b>${voucherDate(c.expiry||c.end)}</b></span><span>Đã cấp<b>${VM.records(c).length} mã</b></span></div></div><div class="actions"></div>`;layout.before(head);if(approval){const buttons=approval.querySelector('.row>div');if(buttons)head.querySelector('.actions').append(...buttons.children);if(c.reviewReason)head.firstElementChild.insertAdjacentHTML('beforeend',`<p class="error">Lý do: ${e(c.reviewReason)}</p>`);approval.remove();}
 const tabs=document.createElement('nav');tabs.className='tabs voucher-tabs';tabs.setAttribute('aria-label','Chi tiết chiến dịch');tabs.innerHTML=`<button type="button" data-panel="config" onclick="voucherShowPanel('config')">Cấu hình chiến dịch</button><button type="button" data-panel="codes" onclick="voucherShowPanel('codes')">${VM.type(c)==='BOOKESE_PUBLIC'?'Mã & lượt sử dụng':'Kho mã & lịch sử cấp'}</button>`;head.after(tabs);layout.dataset.panel='config';if(codes){codes.dataset.panel='codes';codes.classList.add('voucher-codes-head');const search=document.createElement('label');search.className='field';search.innerHTML='Tìm mã hoặc tài khoản<input type="search" placeholder="Nhập mã hoặc tài khoản">';codes.querySelector('.row').after(search);search.querySelector('input').oninput=ev=>codes.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(ev.target.value.toLowerCase()));}voucherShowPanel(voucherPanel);
 }
};
function updateVoucherGuide(){const f=$('#cf'),t=f.voucherType.value;document.querySelectorAll('[data-kind]').forEach(b=>{b.classList.toggle('active',b.dataset.kind===t);b.setAttribute('aria-pressed',b.dataset.kind===t)});$('#voucherGuideTitle').textContent=t;$('#voucherGuideText').textContent=t==='BOOKESE_PUBLIC'?'Lưu cấu hình → gửi duyệt → phát hành mã để khách dùng tại thanh toán.':t==='BOOKESE'?(f.issueMode.value==='direct'?'Phát hành chiến dịch, sau đó mở Kho mã để cấp mã cho đúng tài khoản.':'Phát hành chiến dịch, sau đó tạo quà liên kết tại Danh sách quà tặng.'):'Lưu chiến dịch, nhập giftcode trong Kho mã, rồi phát hành và tạo quà liên kết.';const a=document.querySelector('[data-jump="1"]');if(a)a.hidden=t==='PARTNER';}
function voucherShowPanel(panel){voucherPanel=panel;document.querySelectorAll('[data-panel]').forEach(el=>{if(el.tagName==='BUTTON'){el.classList.toggle('active',el.dataset.panel===panel);el.setAttribute('aria-pressed',el.dataset.panel===panel)}else el.hidden=el.dataset.panel!==panel})}
function giftActualType(g){return g.giftType||'VOUCHER'}
function giftActualStatus(g){const c=db.campaigns.find(x=>x.id===g.campaign),end=g.limited?g.limitEnd:c?.expiry||g.exchangeEnd;return end&&end<VM.today()?'Hết hạn':g.status||'Ẩn'}
function giftGoPage(p){giftPage=p;gifts()}
gifts=function(){
 const rows=db.gifts.filter(g=>(!giftStatus||giftActualStatus(g)===giftStatus)&&(!giftTypeFilter||giftActualType(g)===giftTypeFilter)&&g.name.toLowerCase().includes(giftQuery.toLowerCase()));giftPage=Math.min(giftPage,Math.max(1,Math.ceil(rows.length/10)));
 $('#app').innerHTML=title('Danh sách quà tặng','Quà tặng / Danh sách quà tặng')+`<section class="card"><form id="giftSearch" class="voucher-toolbar">${field('Tìm kiếm','q','search',giftQuery,'placeholder="Tìm kiếm theo Tên quà tặng"')}${select('Bộ lọc','kind',[['','Theo Loại quà'],['VOUCHER','Quà Voucher'],['EXCLUSIVE','Quà Độc Quyền']],giftTypeFilter)}<button type="button" onclick="giftQuery='';giftTypeFilter='';giftStatus='';giftPage=1;gifts()">Nhập lại</button><button class="primary">Tìm kiếm</button></form></section><section class="card gift-screen"><div class="row"><nav class="tabs voucher-tabs" aria-label="Trạng thái quà tặng">${[['','Tất cả'],['Công khai','Công khai'],['Ẩn','Ẩn'],['Hết hạn','Hết hạn']].map(([v,l])=>`<button class="${v===giftStatus?'active':''}" aria-pressed="${v===giftStatus}" onclick="giftStatus='${v}';giftPage=1;gifts()">${l}</button>`).join('')}</nav><button class="orange" onclick="editing=null;location.hash='gift'">＋ Thêm quà tặng</button></div><p><b>${rows.length} quà tặng</b></p><div class="table"><table class="voucher-table"><thead><tr><th>Tên quà</th><th>Loại quà</th><th>Chiến dịch voucher</th><th>Giá quy đổi</th><th>Số lượng quà / Đã đổi</th><th>Hạn sử dụng</th><th>Trạng thái</th><th></th></tr></thead><tbody>${rows.slice((giftPage-1)*10,giftPage*10).map(g=>{const c=db.campaigns.find(x=>x.id===g.campaign),qty=c?(VM.type(c)==='PARTNER'?(c.codes||[]).length:c.quota):g.stock;return `<tr><td class="name"><div class="gift-cell">${g.image?`<img class="gift-thumb" src="${e(g.image)}" alt="${e(g.name)}" width="64" height="64">`:'<span class="gift-thumb" aria-label="Chưa có ảnh">♧</span>'}<div><button onclick="editing='${g.id}';location.hash='gift'">${e(g.name)}</button><small>ID: #${e(g.id.slice(0,12))}</small></div></div></td><td>${g.limited?'Quà giới hạn':giftActualType(g)==='EXCLUSIVE'?'Quà Độc Quyền':'Voucher'}${g.limited?`<small>${voucherDate(g.limitStart)} – ${voucherDate(g.limitEnd)}</small>`:''}</td><td>${e(c?.name||'—')}${c?`<small>${VM.type(c)}</small>`:''}</td><td>${voucherNum(g.price)} Bcoin</td><td>${voucherNum(qty)} / ${(db.voucherExchanges||[]).filter(r=>r.giftId===g.id).length}</td><td>${voucherDate(c?.expiry||g.exchangeEnd||g.limitEnd)}</td><td>${voucherBadge(giftActualStatus(g))}</td><td><button onclick="editing='${g.id}';location.hash='gift'">Xem / sửa</button></td></tr>`}).join('')||'<tr><td colspan="8"><div class="voucher-empty"><b>Chưa có quà tặng phù hợp</b><p>Thay đổi bộ lọc hoặc thêm quà tặng mới.</p></div></td></tr>'}</tbody></table></div>${voucherPager(rows.length,giftPage,'giftGoPage')}</section>`;$('#giftSearch').onsubmit=ev=>{ev.preventDefault();giftQuery=ev.target.q.value.trim();giftTypeFilter=ev.target.kind.value;giftPage=1;gifts()};
};
function giftRadios(label,name,values,value){return `<fieldset><legend>${label}</legend><div class="checks">${values.map(([v,l])=>`<label><input type="radio" name="${name}" value="${v}" ${v===value?'checked':''}>${l}</label>`).join('')}</div></fieldset>`}
function giftStepper(label,name,value,min=0){return `<label class="field">${label}<span class="stepper"><button type="button" aria-label="Giảm ${label}" onclick="this.nextElementSibling.stepDown();this.nextElementSibling.dispatchEvent(new Event('change',{bubbles:true}))">−</button><input type="number" name="${name}" value="${Number(value||0)}" min="${min}" required><button type="button" aria-label="Tăng ${label}" onclick="this.previousElementSibling.stepUp();this.previousElementSibling.dispatchEvent(new Event('change',{bubbles:true}))">＋</button></span></label>`}
giftForm=function(){
 const g=db.gifts.find(x=>x.id===editing)||{},options=db.campaigns.filter(c=>VM.type(c)==='PARTNER'||VM.type(c)==='BOOKESE'&&(c.issueMode||'exchange')==='exchange');let image=g.image||'';
 $('#app').innerHTML=title(editing?'Chỉnh sửa quà':'Thêm quà mới','Quà tặng / Danh sách quà tặng / '+(editing?'Chỉnh sửa quà':'Thêm quà mới'))+`<form id="gf" class="narrow gift-form"><section class="card gift-banner"><svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M5 15h30v8H5zM8 23v14h24V23M20 15v22M20 15C2 15 10 0 20 15Zm0 0C38 15 30 0 20 15Z" stroke-width="2.5"/></svg><div><h2 id="giftFormTitle">Quà Voucher</h2><p class="muted">Thiết lập thông tin quà, giá quy đổi và điều kiện sử dụng.</p></div></section><section class="card"><h2>Thông tin cơ bản</h2>${field('Tên quà tặng','name','text',g.name,'required maxlength="50" placeholder="Nhập tên quà tặng"')}<small class="counter" data-count="name"></small>${giftRadios('Hình thức vận chuyển','delivery',[['EMAIL','Gửi qua Email'],['EXPRESS','Giao hàng']],g.delivery||'EMAIL')}${giftRadios('Loại quà','giftType',[['EXCLUSIVE','Quà Độc Quyền'],['VOUCHER','Quà Voucher']],giftActualType(g))}<div id="giftLink">${select('Chiến dịch voucher','campaign',[['','Chọn chiến dịch voucher'],...options.map(c=>[c.id,c.name+' · '+VM.type(c)])],g.campaign)}<p class="hint" id="giftCampaignHint"></p></div><fieldset><legend>Thuộc tính</legend><label><input type="checkbox" name="limited" ${g.limited?'checked':''}> Quà giới hạn</label></fieldset><div id="giftLimitDates" class="fields">${field('Giới hạn thời gian từ','limitStart','date',g.limitStart)}${field('Đến','limitEnd','date',g.limitEnd)}</div>${giftRadios('Trạng thái','status',[['Ẩn','Ẩn'],['Công khai','Công khai']],g.status==='Công khai'?'Công khai':'Ẩn')}</section><section class="card"><h2>Giá trị & Tồn kho</h2><div class="fields">${field('Giá đổi điểm (Xu)','price','number',g.price,'min="1" required')}${giftStepper('Giới hạn đổi của một tài khoản','limit',g.limit||1,1)}<div id="giftStock">${giftStepper('Số lượng trong kho','stock',g.stock||0)}</div></div><p class="muted" id="giftStockHint"></p></section><section class="card"><h2>Ảnh đại diện</h2><div class="gift-upload"><img id="giftImagePreview" ${image?'':'hidden'} ${image?`src="${e(image)}"`:''} alt="Ảnh quà tặng"><label for="giftImage">THÊM ẢNH</label><input id="giftImage" type="file" accept="image/*"><small>Chọn ảnh JPG, PNG hoặc WebP, tối đa 2 MB.</small></div></section><section class="card"><h2>Nội dung chi tiết</h2>${['description','usage','terms'].map((k,i)=>`<label class="field">${['Mô tả ngắn','Cách sử dụng','Điều kiện áp dụng'][i]}<textarea name="${k}" maxlength="1000" required>${e(g[k])}</textarea></label><small class="counter" data-count="${k}"></small>`).join('')}</section><div id="formerror" class="error" role="alert"></div><div class="footbar"><button type="button" onclick="location.hash='gifts'">Hủy</button><button class="primary">${editing?'Lưu thay đổi':'Tạo'}</button></div></form>`;
 const f=$('#gf');function update(){const voucher=f.giftType.value==='VOUCHER',c=options.find(x=>x.id===f.campaign.value);$('#giftFormTitle').textContent=voucher?'Quà Voucher':'Quà Độc Quyền';$('#giftLink').hidden=!voucher;f.campaign.disabled=!voucher;f.campaign.required=voucher;$('#giftStock').hidden=voucher;f.stock.disabled=voucher;$('#giftStockHint').textContent=voucher?(c?`Còn ${VM.stock(c)} mã có thể cấp từ chiến dịch liên kết.`:'Tồn kho được lấy từ chiến dịch voucher đã chọn.'):'Quà Độc Quyền sử dụng số lượng trong kho của quà.';$('#giftCampaignHint').textContent=c?(VM.type(c)==='BOOKESE'?'Đổi xu để nhận mã riêng cho tài khoản, dùng tại thanh toán Bookese.':'Đổi xu để nhận giftcode dùng tại '+(c.partner||'đối tác')+'.'): 'Chọn BOOKESE đổi xu hoặc PARTNER. Mã công khai và mã CS cấp bù không dùng để tạo quà.';$('#giftLimitDates').hidden=!f.limited.checked;f.limitStart.disabled=f.limitEnd.disabled=!f.limited.checked;f.limitStart.required=f.limitEnd.required=f.limited.checked;const email=f.querySelector('[name=delivery][value=EMAIL]');email.disabled=!voucher;if(!voucher)f.delivery.value='EXPRESS';f.querySelectorAll('[data-count]').forEach(el=>{const input=f.elements[el.dataset.count];el.textContent=input.value.length+' / '+input.maxLength})}f.onchange=update;f.oninput=update;update();
 $('#giftImage').onchange=ev=>{const file=ev.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){$('#formerror').textContent='Chọn ảnh JPG, PNG hoặc WebP không quá 2 MB.';ev.target.value='';return}const r=new FileReader();r.onload=()=>{image=r.result;$('#giftImagePreview').src=image;$('#giftImagePreview').hidden=false;$('#formerror').textContent=''};r.readAsDataURL(file)};
 f.onsubmit=ev=>{ev.preventDefault();const v=Object.fromEntries(new FormData(f)),c=options.find(x=>x.id===v.campaign),fail=m=>$('#formerror').textContent=m;v.limited=f.limited.checked;if(v.limited&&v.limitEnd<v.limitStart)return fail('Ngày kết thúc giới hạn phải từ ngày bắt đầu.');if(v.giftType==='VOUCHER'&&!c)return fail('Chọn chiến dịch voucher.');if(v.status==='Công khai'&&v.giftType==='VOUCHER'&&(!VM.active(c)||!VM.stock(c)))return fail('Chiến dịch phải đang cấp mã và còn số lượng trước khi công khai quà.');if(v.status==='Công khai'&&v.giftType==='EXCLUSIVE'&&Number(v.stock)<1)return fail('Nhập số lượng trong kho trước khi công khai quà.');const next={...g,...v,campaign:v.giftType==='VOUCHER'?v.campaign:'',image,id:editing||crypto.randomUUID(),partner:c?.partner||g.partner||'Bookese'};db.gifts=editing?db.gifts.map(x=>x.id===editing?next:x):[...db.gifts,next];save('Lưu quà '+v.name);location.hash='gifts'};
};
window.addEventListener('hashchange',()=>{if(['#gifts','#gift','#campaigns','#campaign'].includes(location.hash))window.scrollTo(0,0)});
nav();
